### ISSUE TITLE
viewport

### ISSUE THREAD

**Issue by fujunustc** [gpac/gpac#1009]
Hey, Is there some way to get current viewport information?

**Comment by jeanlf** [comment]
VP is given by current camera (in GF_TraverseState) target, position and up vector. It is currently not exposed to the DASH client in 360, but translated into a visibility hint (0% hidden, 100% completely in).
If you need more you may play with gf_mo_hint_visible_rect to expose to the DASH client the visible parts of the frame(s), but that's a bit more complicated in 360 EQR since this will not be a rectangle ...
