### ISSUE TITLE
 Build GPAC for Windows using GPAC_STATIC_MODULES

### ISSUE THREAD

**Issue by wangbo314** [gpac/gpac#1304]
I want to  Build GPAC for Windows  and using GPAC_STATIC_MODULES option，but I get  “error LNK2001	gf_register_module_atsc_in". Please tell me how to fix this problem. Thanks!

**Comment by aureliendavid** [comment]
hm, never tried that on windows, I don't know that it's possible

are you building with visual studio and the gpac.sln solution? I guess you would need to change each module project to be a .lib instead of a .dll and then adjust the dependencies so they all link together

sounds like a hassle 

maybe building with mingw/gcc + configure & make would work? I'm not sure
