### ISSUE TITLE
Batch command that will extract only timed text (sbtl:tx3g) format files and convert to .srt

### ISSUE THREAD

**Issue by olpdog** [gpac/gpac#1308]
I'm playing around with mp4box and I would like to create a batch file that would grab all the "sbtl:tx3g" timed text files from an .mp4 file, convert them to .srt and label the resulting .srt files something like [mp4filetitle].[subtitlelanguage].srt. Only a fraction of these .mp4 files will contain any timed text files, so I want the batch command to continue on even if it doesn't find a timed text file in a particular .mp4 file. Any suggestions would be appreciated. Thank you

**Comment by jeanlf** [comment]
You can get track info by analyzing the -info command, then check for tx3g
Since this can be a bit heavy, I just added an option to get the track count of a file (`-tracks source.mp4`, returns track count on stdout) and an option to get the info of a track by number rather than by ID (`-infon 1`), this should simplify your process.
