### ISSUE TITLE
Is there someways to show merged different resolution hevc tiles in same size?

### ISSUE THREAD

**Issue by chenminnj** [gpac/gpac#1358]
When I play the testcase 'hevcsplit.sh' 's result file merge3.hvc,I get the screen as the below image:
![1](https://user-images.githubusercontent.com/29446122/69319025-57b0c480-0c79-11ea-808b-3d86ec589856.jpg)

The merged high resolution tile(448*208) and low resolution tile(192*128) were showed in different size.Is there someways to show merged different resolution hevc tiles in same size? 

my gpac version is :**version 0.9.0-DEV-rev2882-g045c7de16-filters**

**Comment by jeanlf** [comment]
This is the expected result since you are merging tiles with different size in a single HEVC bitstream. If you want the tiles to be shown with the same resolution, this is not possible using a single bitstream/simple video display, you need a composition layer to handle the upscaling. Check either the compositor filter (if you are familiar with bt/bifs or svg) or the jsfilter to do the composition:
- https://github.com/gpac/gpac/wiki/compositor
- https://github.com/gpac/gpac/wiki/jsf (see testsuite/media/jsf and https://doxygen.gpac.io/group__jsapi__grp.html)

You can either use the composition layer to draw the two independent bitstreams (2 decoders), or keep a single merged bitstream but use the composition layer to upscale the low part of the video (eg through texture coordinates in openGL for example).
