### ISSUE TITLE
How to replace tileagg with hevcmerge

### ISSUE THREAD

**Issue by beibeii** [gpac/gpac#1360]
MP4client uses tileagg by default, can I replace it with hevcmerge, how to configure it, thank you

**Comment by jeanlf** [comment]
ATM the answer is no, MP4Client input pipeline is not user configurable. tileagg is dynamically inserted whenever a regular hvc2/hvt1 input is detected, but that cannot be the case for hevcmerge since the input streams will all be regular HEVC streams. We need to think about how to handle this gracefully. Meanwhile you can try to play with gf_scene_ns_connect_object to inject hevcmerge between the source pipeline and the compositor

**Comment by jeanlf** [comment]
Forgot to add that you can obviously also test demux+hevcmerge+compose+vout filter chain, which is pretty much identical to MP4Client except for user interactivity handling

**Comment by beibeii** [comment]
thanks
