### ISSUE TITLE
Dump Chapter Commands Not Working (Windows)

### ISSUE THREAD

**Issue by LeeThompson** [gpac/gpac#1374]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

--

`MP4Box - GPAC version 0.8.0-rev95-g00dfc933-master`
`Windows 10 18363.535 x64`

Trying to use mp4box to extract chapter information from HandBrake encoded mp4 files.

If I use` -dump-chap` or `-dump-chap-ogg` I get an empty file.
If I try `-raw 5` I get errors and an unusable binary file.

I'm pretty sure HandBrake doesn't quite create chapters the way mp4box (and perhaps other software) like.   That's actually why I'm trying to extract them so I can use mp4box -chap and have them added properly.    

Currently I'm using GUI tools to do this but I'd rather this be more automated.

```
mp4box "Filename.mp4" -dump-chap
[iso file] Found stts entry with sample_delta=0 - forbidden ! Fixing to 1
[iso file] Found stts entry with sample_delta=0 - forbidden ! Fixing to 1
[iso file] Found stts entry with sample_delta=0 - forbidden ! Fixing to 1
[iso file] Found stts entry with sample_delta=0 - forbidden ! Fixing to 1
[iso file] Found stts entry with sample_delta=0 - forbidden ! Fixing to 1
```
mp4box "Filename.mp4" -raw 5
```
[iso file] Found stts entry with sample_delta=0 - forbidden ! Fixing to 1
[iso file] Found stts entry with sample_delta=0 - forbidden ! Fixing to 1
[iso file] Found stts entry with sample_delta=0 - forbidden ! Fixing to 1
[iso file] Found stts entry with sample_delta=0 - forbidden ! Fixing to 1
[iso file] Found stts entry with sample_delta=0 - forbidden ! Fixing to 1
Extracting Track (type 'text') - Compressor Unknown
```
[Filename_track5.zip](https://github.com/gpac/gpac/files/4007614/Filename_track5.zip)

mp4box -info (Chapter Data in Track 5):
```
* Movie Info *
	Timescale 1000 - 5 tracks
	Computed Duration 00:25:35.424 - Indicated Duration 00:25:35.467
	Fragmented File: no
	File suitable for progressive download (moov before mdat)
	File Brand mp42 - version 512
		Compatible brands: isom iso2 mp41


	Created: GMT Sat Dec 28 21:15:25 2019
	Modified: GMT Sat Dec 28 21:15:25 2019

File has no MPEG4 IOD/OD

iTunes Info:
	Encoder Software: HandBrake 1.3.0 2019112400
1 UDTA types: meta (1) 

Track # 1 Info - TrackID 1 - TimeScale 90000
Media Duration 00:25:35.367 - Indicated Duration 00:25:35.367
Track has 1 edit lists: track duration is 00:25:35.368
Media Info: Language "Undetermined (und)" - Type "vide:hvc1" - 36812 samples
Visual Info: width=720 height=480 (depth=24 bits)
Visual Track layout: x=0 y=0 width=640 height=480
MPEG-4 Config: Visual Stream - ObjectTypeIndication 0x23
HEVC Video - Visual Size 720 x 480
	HEVC Info: Profile Main @ Level 3 - Chroma Format YUV 4:2:0

	NAL Unit length bits: 32 - general profile compatibility 0x60000000

	Parameter Sets: 1 VPS 1 SPS 1 PPS 
	SPS resolution 720x480 - Pixel Aspect Ratio 8:9 - Indicated track size 640 x 480
	Bit Depth luma 8 - Chroma 8 - 1 temporal layers
	VPS#1 hash: AC7A95FE5464AE184BC682C3E3E49B7F25A5C2D8
	SPS#1 hash: C9C7EC6DC5B3AF54082C8D580C5D3A96B456F8A2
	PPS#1 hash: A9C81C9127C8A170BF3C2F715BB374C875DF59DC

Self-synchronized
	RFC6381 Codec Parameters: hvc1.1.6.L90.90
	Average GOP length: 117 samples

Track # 2 Info - TrackID 2 - TimeScale 48000
Media Duration 00:25:35.466 - Indicated Duration 00:25:35.466
Track has 1 edit lists: track duration is 00:25:35.424
Media Info: Language "English (eng)" - Type "soun:mp4a" - 71975 samples
2 UDTA types: name (1) titl (1) 
MPEG-4 Config: Audio Stream - ObjectTypeIndication 0x40
MPEG-4 Audio AAC LC (AOT=2 implicit) - 2 Channel(s) - SampleRate 48000
Synchronized on stream 1
	RFC6381 Codec Parameters: mp4a.40.2
Alternate Group ID 1
	All samples are sync

Track # 3 Info - TrackID 3 - TimeScale 90000
Media Duration 00:25:33.289 - Indicated Duration 00:25:33.289
Track has 1 edit lists: track duration is 00:25:33.290
Media Info: Language "English (eng)" - Type "subp:mp4s" - 819 samples
MPEG-4 Config: NeroDigital Subpicture Stream - ObjectTypeIndication 0xe0
Synchronized on stream 1
	RFC6381 Codec Parameters: mp4s.E0
Alternate Group ID 3
	All samples are sync

Track # 4 Info - TrackID 4 - TimeScale 90000
Media Duration 00:25:33.097 - Indicated Duration 00:25:33.097
Track has 1 edit lists: track duration is 00:25:33.097
Track is disabled
Media Info: Language "English (eng)" - Type "sbtl:tx3g" - 821 samples
Unknown Text Stream
 Size 640 x 72 - Translation X=0 Y=0 - Layer 0
	RFC6381 Codec Parameters: tx3g
Alternate Group ID 3
	All samples are sync

Track # 5 Info - TrackID 5 - TimeScale 1000
Media Duration 00:25:35.325 - Indicated Duration 00:25:35.325
Track has 1 edit lists: track duration is 00:25:35.325
Track is disabled
Media Info: Language "Undetermined (und)" - Type "text:text" - 10 samples
Unknown Text Stream
 Size 0 x 0 - Translation X=0 Y=0 - Layer 0
	RFC6381 Codec Parameters: text
	All samples are sync
```

**Comment by LeeThompson** [comment]
I want to add that if chapters are added successfully with mp4box -chap the two extract commands work as expected.     

Having said that, it would be nice if mp4box's extract commands were more liberal in their handling so mp4 containers could be updated (.e.g mp4box FILE -dump-chap && mp4box FILE -chap FILE.chap) in an efficient manner.

**Comment by jeanlf** [comment]
could you upload a test mp4 file (your zip only contains an extracted text file) ?

Also, could you elaborate on your comment on extract commands?

**Comment by LeeThompson** [comment]
@jeanlf I've encoded a sample video (attached as 1374_sample.zip), it's converted from a MKV where I placed 10 chapters at 1 second intervals and converted to MP4 with HandBrake.    The chapters work in various players but mp4box fails to extract them in a usable form.


`mp4box -dump-chap 1374_sample.mp4` produces a zero-byte `1374_sample.chap` file.
`mp4box -raw 3 1374_sample.mp4` produces a binary chapter data file that it doesn't understand for importing as a chapter file (oddly it doesn't throw any errors if you try to import with it) (attached as 1374_sample_track3.zip).

Ideally, it would be nice if mp4box could extract the chapter "text" track as a proper chap file so that batch chapter correction processing could be done such as "`mp4box -dump-chap FILE.mp4 && mp4box FILE.mp4 -chap FILE.chap`".

[1374_sample.zip](https://github.com/gpac/gpac/files/4028982/1374_sample.zip)
[1374_sample_track3.zip](https://github.com/gpac/gpac/files/4028992/1374_sample_track3.zip)

**Comment by jeanlf** [comment]
should now be fixed in master, could you check ?

More details:
Chaptering is a bit messy due to old formats using UDTA at moov level to describe chapters, this was what was implemented by -chap and -dump-chap. I added support for dumping and importing chapter tracks (text:text or text:tx3g) through the same logic:
- `-dump-chap` on a file using chapter tracks will result in a ttxt file being dumped
- `-chap` with a ttxt source will create a new text track and set the proper track references on all video and audio tracks

Note that `-chap`will trash all previous chapter information. If you need to add a new chapter track (eg different language), you will need to use `-add chapter.ttxt:chap:lang=fr` 

The behaviour of `-raw`on text tracks is as expected (used to dump the content of the samples for inspection), you need to use -ttxt for a full XML conversion of the track. I'll check why the importer doesn't complain on the raw file

**Comment by LeeThompson** [comment]
Thanks, will check it out after the nightly build is up.  (I'm not set up to compile this.)

**Comment by jalba69** [comment]
Hello,

Did not had much time to test for now, only checking dumps but something seems odd, on the video from the 1374_sample.zip provided by LeeThompson, those commands used with 0.8.0-rev129-g84fcc59bf-master own compiled with gpac_mp4box_mini.sln :  

```
mp4box -dump-chap 1374_sample.mp4
mp4box -dump-chap-ogg 1374_sample.mp4
```
creates > 1374_sample_3_text.ttxt ( seems correct chapter file ) 

`mp4box -raw 3 1374_sample.mp4`
creates > 1374_sample_track3.text (.text extension with weird formatting inside)

`mp4box -raw * 1374_sample.mp4`
creates > 
1374_sample_track1.hvc
1374_sample_track2.aac
1374_sample_track3.text (.text with weird formatting inside)

Now my usual go to command to dump all in a mp4 : 
`MP4Box -dump-cover -dump-chap-ogg -raw * -srt * 1374_sample.mp4`

Drops the following files : 

- Video : 1374_sample_track1.hvc
- Audio : 1374_sample_track2.aac
- Chapters ttxt : 1374_sample_3_text.ttxt
- Subs as .srt : 1374_sample_3_text.srt  where the content is this : 
```
1
00:00:00,000 --> 00:00:01,000
Chapter 1

2
00:00:01,000 --> 00:00:02,000
Chapter 2

3
00:00:02,000 --> 00:00:03,000
Chapter 3

4
00:00:03,000 --> 00:00:04,000
Chapter 4

5
00:00:04,000 --> 00:00:05,000
Chapter 5

6
00:00:05,000 --> 00:00:06,000
Chapter 6

7
00:00:06,000 --> 00:00:07,000
Chapter 7

8
00:00:07,000 --> 00:00:08,000
Chapter 8

9
00:00:08,000 --> 00:00:09,000
Chapter 9

10
00:00:09,000 --> 00:00:18,680
Chapter 10
```
> Timings and names seems to match those in 1374_sample_3_text.ttxt
>There is no subs in the input file yet here it seems that mp4box mixes a bit the things and thinks the chapter file is some kind of subtitle and drops it as .srt file.
- and finally it drops this too :  
1374_sample_track3.text  with weird formatting, same as other .text files dumped : 
![2020-01-08_082655](https://user-images.githubusercontent.com/15131985/71958460-a518cf00-31f0-11ea-9716-158d5f987a1a.png)

________________________________________________________

Now with Filters Branch  0.9.0-DEV-rev3063-ge0cfe78c5-filters, using the same go to command to dump all:
`MP4Box -dump-cover -dump-chap-ogg -raw * -srt * 1374_sample.mp4`
 Drops the following ( some with -dump-chap instead of -dump-chap-ogg it seems )  : 
- 1374_sample_track1.hvc
- 1374_sample_track2.aac
- 1374_sample_3_text.ttxt
- 1374_sample_3_text.srt
- 1374_sample_track3.tx3g
> .text file extensions obtained with master version of MP4Box are now tx3g ( did not even knew tx3g could be used for chapters, only knew it could be used for subtitles, learning everyday... ), the content of this file have the same weird formatting as seen on the screenhot above

Haven't had much time to try importing those files back, tried once with Filters branch and got a crash, will try more when i'll have time in the next days and report back if needed.

That's all for now after a very quick test.

Thanks a lot :)

**Comment by jeanlf** [comment]
Thanks for the feedback.
The "weird formatting" is normal, `-raw` on a text/tx3g track exports the raw samples, not the decoded text
I'll check the issue with the change of extension for the raw export between master and filters.
Is it an issue to have the chapter text tracks exported by `-srt *` (they are text tracks after all ...) ? If so maybe we can skip chapter tracks exporting when `-dump-chap` (or `-srt *` ) is already set in the command line ?

**Comment by jalba69** [comment]
Thanks a lot for the infos,
the only problem i can see if for the tools using MP4Box in an automated way maybe.

With last commits on master,  0.8.0-rev140-gafad6b8c1-master ( seems like importing .ttxt with -chap had issues before those last changes, -add xx.ttxt on existing mp4 worked, -chap xx.ttxt was skipping it, but now seems fixed with last version i compiled and works fine ) 

Demuxed all files from the sample video in this page , then created a small .srt file, then importing video + audio + ttxt chaps + subtitles created into mp4 : 

`MP4Box -add 1374_sample_track1.hvc -add 1374_sample_track2.aac -add subtitle.srt:lang=fre:name= -chap 1374_sample_3_text.ttxt -new output.mp4`

then using again the dump all command on this new file : 
`MP4Box -dump-cover -dump-chap-ogg -raw * -srt * output.mp4`

Ending up with all this : 
![2020-01-08_135420](https://user-images.githubusercontent.com/15131985/71979605-6a2d9000-321e-11ea-9555-0d8205541433.png)

One of the .srt's is the correct sub file i created, other is the chapters file as .srt like i posted previously.
One of the tx3g is a list of chapters with weird formatting, other is the subtitles in a weird format too, you said it's normal so no worries for those.

Problem i can see with this is only for ( if ) tools that demux automatically and remux the additional files like cover, subs & chapters, either picking the wrong file needed for subs or adding them all and probably resulting in some weird output for subs :p 

Created an  usual mp4 with  video + audio + cover + .srt + a simple chapters.txt file using this format : 
>CHAPTER01=00:00:00.000
CHAPTER01NAME=Chapter I
CHAPTER02=00:00:00.320
CHAPTER02NAME=Chapter II
CHAPTER03=00:00:10.00

And the demuxing is all good using my dump all command:
![2020-01-08_151050](https://user-images.githubusercontent.com/15131985/71984425-196f6480-3229-11ea-8265-7070a512b9df.png)
 no duplicates there so it's good for me ;)
 
Personally i don't have much content using .ttxt's so i don't think it will hurt me i think, anyways now i know since i visited this topic so i will be warned.

Thanks a lot :)

**Comment by LeeThompson** [comment]
My own test results are below.    It appears to work.  I'm going to test it with more media files from varying sources.

```
MP4Box - GPAC version 0.8.0-rev145-g0f92d1b3-master
(c) Telecom ParisTech 2000-2018 - Licence LGPL v2
GPAC Configuration: (static configuration file)
Features: GPAC_64_BITS GPAC_MEMORY_TRACKING GPAC_HAS_SSL GPAC_HAS_SPIDERMONKEY GPAC_HAS_JPEG GPAC_HAS_PNG
```

`mp4box.exe -dump-chap "1374_sample.mp4"`

```
Chapter track found, dumping to ttxt
[iso file] Unknown box type encd
[iso file] Unknown box type encd
[iso file] Unknown box type encd   | (10/100)
[iso file] Unknown box type encd   | (20/100)
[iso file] Unknown box type encd   | (30/100)
[iso file] Unknown box type encd   | (40/100)
[iso file] Unknown box type encd   | (50/100)
[iso file] Unknown box type encd   | (60/100)
[iso file] Unknown box type encd   | (70/100)
[iso file] Unknown box type encd   | (80/100)
Conversion done
```

(Result is some XML style chapter/text file)

`mp4box.exe -rem 3 -chap "1374_sample_3_text.ttxt" "1374_sample.mp4"`

```
Removing track ID 3
Timed Text (GPAC TTXT) Import
Warning: color badly formatted
Saving 1374_sample.mp4: 0.500 secs Interleaving
```

Result is a "Menu" style chapter track which works.

MediaInfo:

```
Menu
ID                                       : 3
Codec ID                                 : tx3g
Duration                                 : 18 s 680 ms
Encoded date                             : UTC 2020-01-10 20:14:37
Tagged date                              : UTC 2020-01-10 20:14:37
Menu For                                 : 1,2
Duration_LastFrame                       : 8680
00:00:00.000                             : Chapter 1
00:00:01.000                             : Chapter 2
00:00:02.000                             : Chapter 3
00:00:03.000                             : Chapter 4
00:00:04.000                             : Chapter 5
00:00:05.000                             : Chapter 6
00:00:06.000                             : Chapter 7
00:00:07.000                             : Chapter 8
00:00:08.000                             : Chapter 9
00:00:09.000                             : Chapter 10
```

[1374_sample_3_text.zip](https://github.com/gpac/gpac/files/4047755/1374_sample_3_text.zip)
