### ISSUE TITLE
Encoding for pseudo live loop

### ISSUE THREAD

**Issue by chanof** [gpac/gpac#1381]
Hi there, i need to stream a loop with mp4box, mpeg dash, 3 adaption sets the higher 1080p and a stereo track too, do i need to get a video with a duration in seconds multiples of the dash segments duration?
To infinite stable loop purpose.
Thanks

**Comment by jeanlf** [comment]
It depends how you plan on looping the session. If you use `-no-loop`, a new period will be created at each loop so no issue with duration. Otherwise, the looping will work but you might end up with segments that are shorter or longer than the min/max duration allowed in dash (50% of the advertised duration). Not an issue if you use segment timeline (but the MPD will get bigger at each segment), but it can be problematic for some players when using segment templates without timeline.

**Comment by chanof** [comment]
This is my command line:
`MP4Box -dash-live 2000 -subdur 4000 -bound -profile dashavc264:live -mpd-refresh 4 -time-shift 16 -min-buffer 2000 -url-template -insert-utc -run-for 86400000 -dash-ctx /var/www/site.com/public/live/log.txt -out /var/www/site.com/public/live/manifest.mpd 1080set.mp4:bandwidth=4800000#video 720set.mp4:bandwidth=2400000#video 360set.mp4:bandwidth=800000#video 180set.mp4:bandwidth=400000#video audio.mp4:bandwidth=384000#audio`

I use it with video.js/dash.js on browsers

Usually i use to concat more videos, to get a big one video with FFMPEG, but i get issues to obtain a video with the duration in seconds without any decimal, i need to stream this video over and over without no pauses, so the users can't understand when the loop start again. (and they don't need to refresh the player page)
I try to get it more stable i can, so please may i ask you which config i need to choose? i think that -no-loop does not allow me to auto restart, and a little decimal's delta mulitplied over and over as the loop could involve in error.
May i ask which is the better strategy?
Thanks
