### ISSUE TITLE
does mp4box supports MKV for mpeg dash live?

### ISSUE THREAD

**Issue by chanof** [gpac/gpac#1402]
For my purpose i need to use MKV instead mp4 to add wav inside the container instead mp3/aac
It is possible?
Thanks

**Comment by jeanlf** [comment]
you will need latest version of filters branch
`MP4Box -dash 1000 -profile live $source -o res/manifest.mpd:muxtype=mkv`
or
`MP4Box -dash 1000 -profile live $source -o res/manifest.mpd --muxtype=mkv`

(also possible using gpac app)

The source can be any source supported by GPAC.
Note that the playback of the manifest will fail with GPAC due to some issues in the ffmpeg integration. We haven't tested playback with other clients
