### ISSUE TITLE
Please do not hardcode -L/usr/lib

### ISSUE THREAD

**Issue by tpgxyz** [gpac/gpac#1417]
- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Hi,

i've noticed that gpac hardcodes in many places -L/usr/lib which is very wrong is case of x86_64,aarch64, riscv64 and many more 64 bit platforms where libraries are placed in /lib64, /usr/lib64

These hardcodes produces linking errors:
```
/usr/bin/clang -shared "-Wl,-soname,libgpac.so.7" -o ../bin/gcc/libgpac.so utils/os_divers.o utils/os_file.o utils/list.o utils/bitstream.o utils/error.o utils/alloc.o utils/url.o utils/configfile.o  utils/sha1.o  utils/base_encoding.o utils/os_net.o utils/os_thread.o utils/os_config_init.o utils/cache.o utils/downloader.o utils/xml_parser.o utils/utf.o utils/token.o utils/color.o  utils/os_module.o utils/math.o utils/path2d.o utils/path2d_stroker.o utils/module.o utils/uni_bidi.o utils/ringbuffer.o utils/unicode.o utils/map.o  mcrypt/cbc.o mcrypt/cfb.o mcrypt/ctr.o mcrypt/des.o mcrypt/ecb.o mcrypt/g_crypt.o mcrypt/ncfb.o mcrypt/nofb.o mcrypt/ofb.o mcrypt/rijndael-128.o mcrypt/rijndael-192.o mcrypt/rijndael-256.o mcrypt/stream.o mcrypt/tripledes.o  scenegraph/base_scenegraph.o scenegraph/mpeg4_animators.o scenegraph/commands.o scenegraph/mpeg4_nodes.o scenegraph/mpeg4_valuator.o scenegraph/vrml_interpolators.o scenegraph/vrml_proto.o scenegraph/vrml_route.o scenegraph/vrml_script.o scenegraph/vrml_smjs.o scenegraph/vrml_tools.o scenegraph/x3d_nodes.o scenegraph/svg_attributes.o scenegraph/svg_types.o scenegraph/svg_smjs.o scenegraph/smil_anim.o scenegraph/smil_timing.o scenegraph/svg_properties.o scenegraph/dom_events.o  scenegraph/dom_smjs.o scenegraph/xbl_process.o scenegraph/xml_ns.o scenegraph/html5_media_smjs.o scenegraph/html5_mse_smjs.o scenegraph/webvtt_smjs.o ietf/rtcp.o ietf/rtp.o ietf/rtp_packetizer.o ietf/rtp_pck_3gpp.o ietf/rtp_pck_mpeg12.o ietf/rtp_pck_mpeg4.o ietf/rtsp_command.o ietf/rtsp_common.o ietf/rtsp_response.o ietf/rtsp_session.o ietf/sdp.o ietf/rtp_depacketizer.o ietf/rtp_streamer.o bifs/arith_decoder.o bifs/bifs_codec.o bifs/bifs_node_tables.o bifs/com_dec.o bifs/com_enc.o bifs/conditional.o bifs/field_decode.o bifs/field_encode.o bifs/memory_decoder.o bifs/predictive_mffield.o bifs/quantize.o bifs/script_dec.o bifs/script_enc.o bifs/unquantize.o isomedia/avc_ext.o isomedia/box_code_3gpp.o isomedia/box_code_apple.o isomedia/box_code_base.o isomedia/box_code_drm.o isomedia/box_code_meta.o isomedia/box_dump.o isomedia/box_funcs.o isomedia/data_map.o isomedia/drm_sample.o isomedia/isom_intern.o isomedia/isom_read.o isomedia/isom_store.o isomedia/isom_write.o isomedia/media.o isomedia/media_odf.o isomedia/meta.o isomedia/movie_fragments.o isomedia/sample_descs.o isomedia/stbl_read.o isomedia/stbl_write.o isomedia/track.o isomedia/tx3g.o isomedia/iff.o    isomedia/hint_track.o isomedia/hinting.o isomedia/box_code_adobe.o isomedia/ttml.o odf/desc_private.o odf/descriptors.o odf/odf_code.o odf/odf_codec.o odf/odf_command.o odf/qos.o odf/slc.o  odf/ipmpx_code.o odf/oci_codec.o  odf/ipmpx_dump.o odf/ipmpx_parse.o odf/odf_dump.o odf/odf_parse.o media_tools/isom_tools.o media_tools/dash_segmenter.o media_tools/av_parsers.o media_tools/img.o media_tools/media_import.o media_tools/mpegts.o media_tools/m3u8.o media_tools/mpd.o media_tools/dash_client.o  media_tools/media_export.o media_tools/m2ts_mux.o media_tools/filestreamer.o media_tools/avilib.o media_tools/mpeg2_ps.o media_tools/ismacryp.o media_tools/isom_hinter.o media_tools/saf.o media_tools/vobsub.o media_tools/text_import.o media_tools/html5_media.o media_tools/html5_mse.o media_tools/webvtt.o scene_manager/scene_manager.o scene_manager/text_to_bifs.o scene_manager/loader_bt.o scene_manager/loader_xmt.o scene_manager/loader_isom.o scene_manager/loader_qt.o scene_manager/loader_svg.o  scene_manager/swf_parse.o scene_manager/swf_bifs.o scene_manager/swf_svg.o  scene_manager/scene_dump.o scene_manager/scene_stats.o scene_manager/scene_engine.o  scene_manager/encode_isom.o terminal/channel.o terminal/clock.o terminal/decoder.o terminal/term_node_init.o terminal/input_sensor.o terminal/media_control.o terminal/media_manager.o terminal/media_memory.o terminal/media_object.o terminal/media_sensor.o terminal/mpeg4_inline.o terminal/network_service.o terminal/object_browser.o terminal/object_manager.o terminal/scene.o terminal/terminal.o terminal/svg_external.o compositor/audio_input.o compositor/audio_mixer.o compositor/audio_render.o compositor/bindable.o compositor/camera.o compositor/compositor.o compositor/compositor_2d.o compositor/compositor_3d.o compositor/compositor_node_init.o compositor/drawable.o compositor/events.o compositor/font_engine.o compositor/hc_flash_shape.o compositor/hardcoded_protos.o compositor/mesh.o compositor/mesh_collide.o compositor/mesh_tesselate.o compositor/mpeg4_animstream.o compositor/mpeg4_audio.o compositor/mpeg4_background.o compositor/mpeg4_background2d.o compositor/mpeg4_bitmap.o compositor/mpeg4_composite.o compositor/mpeg4_form.o compositor/mpeg4_geometry_2d.o compositor/mpeg4_geometry_3d.o compositor/mpeg4_geometry_ifs2d.o compositor/mpeg4_geometry_ils2d.o compositor/mpeg4_gradients.o compositor/mpeg4_grouping.o compositor/mpeg4_grouping_2d.o compositor/mpeg4_grouping_3d.o compositor/mpeg4_layer_2d.o compositor/mpeg4_layer_3d.o compositor/mpeg4_layout.o compositor/mpeg4_lighting.o compositor/mpeg4_path_layout.o compositor/mpeg4_sensors.o compositor/mpeg4_sound.o compositor/mpeg4_text.o compositor/mpeg4_textures.o compositor/mpeg4_timesensor.o compositor/mpeg4_viewport.o compositor/navigate.o compositor/offscreen_cache.o compositor/svg_base.o compositor/svg_filters.o compositor/svg_font.o compositor/svg_geometry.o compositor/svg_grouping.o compositor/svg_media.o compositor/svg_paint_servers.o compositor/svg_text.o compositor/texturing.o compositor/texturing_gl.o compositor/visual_manager.o compositor/visual_manager_2d.o compositor/visual_manager_2d_draw.o compositor/visual_manager_3d.o compositor/visual_manager_3d_gl.o compositor/x3d_geometry.o laser/lsr_enc.o laser/lsr_dec.o laser/lsr_tables.o -lm -L/usr/lib -lGL -lGLU -lX11 -lz -lssl -lcrypto -ljpeg -lpng -logg -lpthread -ldl	 -Os -fomit-frame-pointer -g1 -Wstrict-aliasing=2 -pipe  -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4  -m64 -mtune=generic -flto -Ofast -Wl,-O2  -Wl,--no-undefined -flto  -Os -fomit-frame-pointer -g1 -Wstrict-aliasing=2 -pipe  -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4  -m64 -mtune=generic -flto -Ofast -Wl,-O2  -Wl,--no-undefined -flto  -Wl,--warn-common -Wl,-z,defs
make[1]: Leaving directory '/builddir/build/BUILD/gpac-0.7.1/src'
BUILDSTDERR: ld: error: /usr/bin/../lib64/gcc/x86_64-openmandriva-linux-gnu/10.0.0/../../../../lib64/crti.o is incompatible with elf_x86_64
BUILDSTDERR: ld: error: /usr/bin/../lib64/gcc/x86_64-openmandriva-linux-gnu/10.0.0/crtbeginS.o is incompatible with elf_x86_64
BUILDSTDERR: ld: error: /usr/bin/../lib64/gcc/x86_64-openmandriva-linux-gnu/10.0.0/crtfastmath.o is incompatible with elf_x86_64
BUILDSTDERR: ld: error: utils/os_divers.o is incompatible with elf_x86_64
BUILDSTDERR: ld: error: utils/os_file.o is incompatible with elf_x86_64
BUILDSTDERR: ld: error: utils/list.o is incompatible with elf_x86_64
BUILDSTDERR: ld: error: utils/bitstream.o is incompatible with elf_x86_64
BUILDSTDERR: ld: error: utils/error.o is incompatible with elf_x86_64
BUILDSTDERR: ld: error: utils/alloc.o is incompatible with elf_x86_64
BUILDSTDERR: ld: error: utils/url.o is incompatible with elf_x86_64
BUILDSTDERR: ld: error: utils/configfile.o is incompatible with elf_x86_64
BUILDSTDERR: ld: error: utils/sha1.o is incompatible with elf_x86_64
BUILDSTDERR: ld: error: utils/base_encoding.o is incompatible with elf_x86_64
BUILDSTDERR: ld: error: utils/os_net.o is incompatible with elf_x86_64
BUILDSTDERR: ld: error: utils/os_thread.o is incompatible with elf_x86_64
BUILDSTDERR: ld: error: utils/os_config_init.o is incompatible with elf_x86_64
BUILDSTDERR: ld: error: utils/cache.o is incompatible with elf_x86_64
BUILDSTDERR: ld: error: utils/downloader.o is incompatible with elf_x86_64
BUILDSTDERR: ld: error: utils/xml_parser.o is incompatible with elf_x86_64
BUILDSTDERR: ld: error: utils/utf.o is incompatible with elf_x86_64
BUILDSTDERR: ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
BUILDSTDERR: clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
BUILDSTDERR: make[1]: *** [Makefile:276: ../bin/gcc/libgpac.so] Error 1
RPM build errors:
BUILDSTDERR: make: *** [Makefile:9: all] Error 2
```

We had to hack your configure script and other files to get rid of these hardcodes.
Please add detection of lib place and use -L${libdir} which will point to ${prefix}/lib64 on 64bit platforms and to ${prefix}/lib on 32 bit platforms.

Our changes to make gpac-0.8.0 compile without errors:
https://github.com/OpenMandrivaAssociation/gpac/commit/715c05537b80b5afecddeacecada99c30f01b634

https://github.com/OpenMandrivaAssociation/gpac/commit/52eff3bae2907f7c05284dfc7118bd3b078d0868

https://github.com/OpenMandrivaAssociation/gpac/commit/195ee01ac5a9fa35938c0b1d9a556f38127d026c

**Comment by aureliendavid** [comment]
Hi, 

Thanks for the report. This was more complex that I thought so I'll go into a bit of details to make sure we're on the same page. 

## details

I was suspicious of the issue because we mostly build on 64 bit systems and have never encountered this problem. I was able to reproduce it on a mandriva vm though. The conditions where the problem occurs are:
 * a system with 32bit libraries in `/usr/lib` (and 64bits libs elsewhere)
 * the `prefix` set to `/usr`
 * **and** using clang over gcc

So something like `./configure --prefix=/usr --cc=clang` doesn't link on mandriva.

Turns out the problem (other than our not-great `configure`) comes from the llvm linker (`lld`) versus the gnu linker (`ld`).

The GNU linker just skips libs that aren't for the right arch, and since /lib64 and /usr/lib64 are always in the default search path it will find the right libs eventually. 

However lld seems to try and link with the first lib it founds (which it shouldn't) and throw the error messages in the OP (which are incorrect since the .o files are indeed built for `elf_x86_64`)

There is at least one bug report opened on this subject at llvm: https://bugs.llvm.org/show_bug.cgi?id=42802

## fixes

1.

the first fix, without changing anything to gpac, would be to use another linker; this can be done by adding: 

`--extra-ldflags="-fuse-ld=bfd" `

or 
`
--extra-ldflags="-fuse-ld=gold" `

to the `./configure`

2.

changing linker might not be an option, so we can indeed fix some stuff in our configure/makefiles

> Please add detection of lib place and use -L${libdir} which will point to ${prefix}/lib64 on 64bit platforms and to ${prefix}/lib on 32 bit platforms.

The problem with this approach is that the lib64 dir doesn't seem to be standard and detecting it automatically seems difficult. (see this discussion for example: https://lists.gnu.org/archive/html/autoconf/2010-02/msg00019.html ; debian-likes don't use lib64)

But we can set it manually in the configure (`--libdir=lib64`) so if your build script can set this you should be ok by including the commit above (e4a7a63). 

I changed `$prefix/lib` to `$prefix/$libdir` where relevant. and included a variation of your patches https://github.com/OpenMandrivaAssociation/gpac/commit/715c05537b80b5afecddeacecada99c30f01b634 and https://github.com/OpenMandrivaAssociation/gpac/commit/52eff3bae2907f7c05284dfc7118bd3b078d0868 to remove the unnecessary instances of `-L/usr/lib`.


Please check if one of these solutions fix the issue for you and get back to us.

**Comment by berolinux** [comment]
The lib64 dir is pretty much standard - it was what pretty much everyone agreed on when 64bit platforms first started appearing (the idea being that the filesystem remains compatible with old packages assuming /usr/lib contains 32bit libraries). It is used at least in Red Hat, Fedora, CentOS, OpenMandriva, Mageia, Gentoo, and a few others - pretty much anything but Debian and its derivates.
--libdir=lib64 works for the most part and is already used in our build scripts.

One problem in gpac that we're working around in our patches (which need some cleanup to not break other systems) is that there's already a few checks to avoid adding -L/usr/lib, but they don't work.

static.mak and modules/xvid_dec/Makefile both do

ifneq ($(prefix), /usr)
EXTRALIBS+=-L$(prefix)/lib
endif

The problem there is the space behind the comma in the ifneq statement -- while it follows indentation rules, make interpretes it as a literal space and only matches if $(prefix) is [space]/usr instead of /usr. Unless this is already fixed in master branch, will submit a PR to fix that properly.

**Comment by aureliendavid** [comment]
> 
> static.mak and modules/xvid_dec/Makefile both do
> 
> ifneq ($(prefix), /usr)
> EXTRALIBS+=-L$(prefix)/lib
> endif
> 
> The problem there is the space behind the comma in the ifneq statement -- while it follows indentation rules, make interpretes it as a literal space and only matches if $(prefix) is [space]/usr instead of /usr. Unless this is already fixed in master branch, will submit a PR to fix that properly.

I can't seem to reproduce this behavior: 

```Makefile
$ cat Makefile
prefix=/usr
ifneq ($(prefix), /usr)
all::
        echo 'true'
else
all::
        echo 'false'
endif
```

mandriva 4.1
```
$ make --version
GNU Make 4.3
Built for x86_64-openmandriva-linux-gnu
$ make
echo 'false'
false
```

ubuntu 16.04
```
$ make --version
GNU Make 4.1
Built for x86_64-pc-linux-gnu
$ make
echo 'false'
false
```

macos 10.13
```
$ make --version
GNU Make 3.81
This program built for i386-apple-darwin11.3.0
$ make
echo 'false'
false
```

the make manual also includes a space after the comma: https://www.gnu.org/software/make/manual/html_node/Conditional-Syntax.html#Conditional-Syntax


However, before yesterday's commit (e4a7a63), the condition in `static.mak` was:

```Makefile
ifneq ($(prefix), /usr/local)
EXTRALIBS+=-L$(prefix)/lib
else
ifneq ($(prefix), /usr)
EXTRALIBS+=-L$(prefix)/lib
endif
endif
```

which makes no sense since the second `ifneq` will be evaluated only if prefix==/usr/local so it can't be equal to /usr

I changed it to 

```Makefile
ifneq ($(prefix), /usr/local)
ifneq ($(prefix), /usr)
EXTRALIBS+=-L$(prefix)/lib
endif
endif
```

and so `-L/usr/lib` shouldn't be added when the prefix is `/usr` or `/usr/local`


Do you still have issues with -L/usr/lib after e4a7a63 (and without the PR #1418)?

**Comment by aureliendavid** [comment]
> 
> Do you still have issues with -L/usr/lib after [e4a7a63](https://github.com/gpac/gpac/commit/e4a7a631b91c431e335c4bb8ad9b366f71a8b608) (and without the PR #1418)?

Hi @tpgxyz & @berolinux, 

can you confirm or infirm if the issue is resolved after e4a7a63 or if merging #1418 is still required?

thanks

**Comment by jeanlf** [comment]
Any news on this?

**Comment by tpgxyz** [comment]
@jeanlf  @aureliendavid sorry for the delay, currently i do not have time for this. Anyways i'll try to find some time this week. Please wait with closing this issue, for my feedback.

**Comment by jeanlf** [comment]
sure, thx for the feedback!

**Comment by tpgxyz** [comment]
@jeanlf @aureliendavid  Hi, sorry for the delay. I've adapted [e4a7a63](https://github.com/gpac/gpac/commit/e4a7a631b91c431e335c4bb8ad9b366f71a8b608) to v.0.8.0 and it almost work. Last problematic `/usr/lib` hardcode is here:
https://github.com/gpac/gpac/blob/75a60998103b201e2cd2b984574af8a6f6f32e06/modules/jack/Makefile#L28

Successful build with your commit and fixed hardoced /usr/lib in jack module
https://abf.openmandriva.org/build_lists/762381

**Comment by aureliendavid** [comment]
indeed it looks like I forgot this one, sorry

should be ok as of 810dd58 

thanks for the feedback

**Comment by tpgxyz** [comment]
@aureliendavid Ok, we may close this one. Thanks all.
