### ISSUE TITLE
Why -mfra does not supported in dash mode?(MP4Box )

### ISSUE THREAD

**Issue by LeoKingLong** [gpac/gpac#1433]
-mfra: insert movie fragment random offset when fragmenting file (ignored in dash mode)

Why -mfra does not supported in dash mode?
In mp4 file ,stss Box has the information of I-frame.
![image](https://user-images.githubusercontent.com/26246461/76953179-4175f500-6949-11ea-880d-bbd1bd4fac2d.png)

But when this file dashed, the I-frame information is missing in m4s file.
Is there some command in MP4Box can keep I-frame information into dashed file (m4s file)?
Thanks!

**Comment by jeanlf** [comment]
I frame info is still present in each track run in the fragmented file, but you don't have a global index in this mode.
For DASH in onDemand mode (single file, single segment), I-frame (rather segment) information is in the sidx box right after the moov, rather than in a mfra box at the end of the file.
