### ISSUE TITLE
Controlling max buffer duration in MP4Client

### ISSUE THREAD

**Issue by mdasari823** [gpac/gpac#1444]
Hi,

I looking media_tools/dash_client.c to find the maximum buffer capacity. I found a function gf_dash_group_set_buffer_levels and the variable group->buffer_max_ms that I think are setting the buffer capacity. But it looks like this is being updated for every segment. Why so? Shouldn't the max buffer capacity be a constant in the beginning of the playback? 

Any idea? Thank you.

**Comment by jeanlf** [comment]
It is indeed constant for the time being, but we might want to add the ability to change the max playout buffer dynamically in the near future. The function sets both buffer level and min/maxbuffer limits, which is why it is called at each segment. Note that we could indeed split the function in two functions (one for min/max levels, one for current level) but for now we don't track buffer min/max changes hence a single function
