### ISSUE TITLE
Unable to use dasher with max-chain=0

### ISSUE THREAD

**Issue by VShell** [gpac/gpac#1477]
Can somebody provide an example of using dasher with `-max-chain=0`? I have been trying for the last few hours to take a (once this is working, live) MPEG-TS stream containing h.264 and AAC, and turn it into a DASH stream, and all I've been receiving are hangs, errors and segfaults. For example:

```
> ./gpac/result/bin/gpac -max-chain=0 src=/home/shell/Downloads/big_buck_bunny_480p_stereo.ts m2tsdmx:#Representation=1 rfnalu rfadts dasher:dmode=dynamic:profile=live:muxtype=mp4 mp4mx dst=live.mpd

Dynamic resolution of filter connections disabled

[Dasher] No bitrate property assigned to PID PID256, defaulting to 1Mbps
	Try specifying bitrate property after your source, e.g. -i source.raw:#Bitrate=VAL
[Dasher] No bitrate property assigned to PID PID257, defaulting to 1Mbps
	Try specifying bitrate property after your source, e.g. -i source.raw:#Bitrate=VAL
No filter chain found for PID PID257 in filter mp4mx to any loaded filters - NOT CONNECTED
^Ccatched SIGINT - flush session before exit ? (Y/n):
n
session last connect error Filter not found for the desired type
```

Tested with commit 818f6e9. I've uploaded a copy of the relevant file to https://www.mediafire.com/file/gwh79qwg7f56vdf/big_buck_bunny_480p_stereo.ts/file.

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
You cannot use the dasher with max-chain=0 (I just patched the code to forbid that).

The reason is that the dasher creates new destination files for segments that require graph resolution to instantiate the proper muxer. Even pre-loading a muxer as you tried cannot work, as the dasher assigns run-time properties to both dynamic destinations (segments) and output media PIDs to handle multiplexed vs un-multiplexed cases, and you cannot pre-define these properties. 

Side question is why would you want to disable the graph resolver ? In your case, why not just use:
`gpac -i source.ts -o res/live.mpd:dmode=dynamic:profile=live`

or (same results using global options):
`gpac -i source.ts -o res/live.mpd --dmode=dynamic --profile=live`


Disabling the graph resolver is usually not a good idea: it will require careful setup of filter IDs and sources and may not work with some filters (dasher, dash demux, file concatenator, ...).

**Comment by VShell** [comment]
@jeanlf Thank you - I'd actually worked a lot of that out today! My use case for disabling the graph resolver was to force gpac to fail to work with unexpected source formats. I've fixed this, I think, by setting links up correctly:

```
gpac src=/home/shell/Downloads/big_buck_bunny_480p_stereo.ts:#Representation=original @ m2tsdmx @ rfnalu:FID=1 @1 rfadts:FID=2 dst=live.mpd:dmode=dynamic:profile=live:muxtype=mp4:SID=1,2
```

Does this sound about correct?

**Comment by jeanlf** [comment]
Yes that's one possibility. Note that this will only forward one pid of type AVC/HEVC and one pid of type AAC. You could extend this by setting `:clone`on the rfadts filter.

Other approaches:
- use the -blacklist feature to remove all reframers you don't want , eg
`-blacklist=rfmp3,rfac3`

- or use PID property filtering based on the codec type you want. This is done through fragments on source IDs:
`gpac -i source.ts:FID=S @ -o live.mpd[:options]:SID=S#CodecID=avc,S#CodecID=aac`

I prefer the last approach as it also allows you to filter by language or any other property, and is independent from the source filter used (whereas the first approach could behave differently if ffmpeg input is used).
For example:
`gpac -i source.ts:FID=S @ -o live.mpd[:options]:SID=S#Width-1280,S#Language=eng`
 
This will only forward to the dasher PIDs with english language and PIDs with Width property less than 1280.

I'll add a filtering entry to the howtos that could be useful.
