### ISSUE TITLE
Windows XP  - gpac-0.8.0-rev1-gc1990d5c-master-win32.exe 

### ISSUE THREAD

**Issue by qa58** [gpac/gpac#1490]
With 0.8.0 couldn't find any notation of change of supported Windows operating systems, used PETools to peek how 0.8.0 exes were compiled, was for Windows 6 which is Vista - was that intentional or a mistake? I patched mp4box back to Windows 5.1 (XP) and it runs in XP - except I don't know if the DLLs contain Vista+ Windows API calls and will choke.
Personally, I like to encourage use of Windows 7 SDK documentation so code remains compatible with most versions of Windows - Microsoft makes additions into the Windows API that often I find are not really necessary and if used, serve only to break Vista, XP, etc compatibility.

**Comment by aureliendavid** [comment]
I've looked into this a bit. 

I think the short answer is: XP isn't fully supported anymore, but it still might work. 

Longer answer: 

(there's an interesting similar discussion here: https://github.com/sqlitebrowser/sqlitebrowser/issues/893) 

## PE Header

A while ago we went from Visual Studio 2010 to 2015. The new default since VS2013 for the `MinimumRequiredVersion` field is 6. This value in itself is just a flag in the PE header and can easily be changed before or after compilation. 

## XP compatibiliy 

Now for the more complex question of real XP compatibility, there are 3 major obstacles in our recent codebase:

1. We abandoned enforcing C89 standard in favor of C99 (most notably for declarations after statements and designated initializers). This prevents from using VS2010, the v100 toolset and the 7.1SDK (*). 

2. Incompatible 3rd-party dependencies: in particular ffmpeg dropped xp support so everything linked against ffmpeg libraries won't work (e.g.: libavutil depends on bcrypt.dll which doesn't exist for xp: https://patchwork.ffmpeg.org/project/ffmpeg/patch/20180330124452.4800-1-robux4@ycbcr.xyz/ )

3. Use of more recent windows api calls

[_(*) To clarify; that doesn't mean it won't work on windows 7. It will. The windows 7.1 sdk is just the last version to provide full xp support_]

Now to add another layer of complexity: these 3 factors impact our 2 main gpac version (0.8.x legacy branch, and 0.1.x master branch) very differently. 

## legacy branch (0.8.x)

For legacy, as mentioned in the OP, once the PE header is modified, the binaries that we distribute in our installer mostly work. 

The `gm_ffmpeg_in.dll` module won't work (for reason 2.) but `MP4Box` seem pretty much ok. 

For this reason, it makes sense for the legacy branch to set the `MinimumRequiredVersion` back down to 5 (5.1 for 32bits and 5.2 for 64bits) so that our installers can be used on windows xp albeit with some limitations. 

I did that in 47fb157 and tested [gpac-0.8.1-rev3-g47fb1575-legacy-win32.exe](https://download.tsi.telecom-paristech.fr/gpac/legacy_builds/win32/gpac-0.8.1-rev3-g47fb1575-legacy-win32.exe) on a windows xp sp3 successfully. 

## master branch (0.1.x) 

For master XP compatibility is pretty much hopeless. At least our installers won't work with trivial changes. 

The reasons are: more recent api calls, and the way the binaries are linked make issue 2. above much more prevalent. 

There is a way to build a custom static MP4Box-only binary that will work on xp by:

 - using the `Release - MP4Box_only` build profile
 - setting the `MinimumRequiredVersion` down to 5.x
 - unsetting `GPAC_HAS_IPV6` in [utils/os_net.c:55](https://github.com/gpac/gpac/blob/master/src/utils/os_net.c#L55) (due to usage of `inet_ntop()`)

With these settings it seems to work currently. However there are no guarantee that future commits won't introduce more xp-incompatible calls. 

Since in any case it requires a custom build, I haven't changed anything in master for our official builds. 

<hr />

So that's what I could test and find out. I personnally don't know how much time we should inverst on xp support. I feel like having 0.8.1 mostly work might be good enough considering the OS is 18 years old and it's been 6 years since microsoft has stopped extended support.

**Comment by jeanlf** [comment]
thanks for the very detailed report @aureliendavid ! I think we should add this in the build section on the wiki no?

**Comment by aureliendavid** [comment]
[good edit :)]

> thanks for the very detailed report @aureliendavid ! I think we should add this in the build section on the wiki no?

sure, we can link to the issue on the windows build page for example

**Comment by jeanlf** [comment]
done, and closing
