### ISSUE TITLE
Support for generating dash based encrypted m4s files with muxed audio and video 

### ISSUE THREAD

**Issue by suhaskam** [gpac/gpac#1505]
Is there any support for the below requirement ?

Given a video file containing audio and video.

Generate mpd and m4s files. 
The m4s files should have audio and video muxed and also encrypted using using clear key.

**Comment by suhaskam** [comment]
Also , will the generated contents be playable by shaka player ?

**Comment by jeanlf** [comment]
MP4Box and gpac (0.9.0) can both be used to generate such files.

For the muxing part, you can check [this test](https://github.com/gpac/testsuite/blob/filters/scripts/dash-mux-ondemand.sh).
If you plan on using the gpac app, sources to be combined in a same mux must be assigned a representation otherwise they are automatically in different mux (this is different from MP4Box where all tracks of a file are by default assigned the same representation). For example:
```
gpac -i source.mp4:#Representation=MyRep -o dash/session.mpd
```
This will create a muxed output

```
gpac -i source.mp4 -o dash/session.mpd
```
This will create non-muxed outputs

For the encryption part, you can check [this test](https://github.com/gpac/testsuite/blob/filters/scripts/encryption.sh).

No clue if Shaka player supports multiplexed representation ([this](https://github.com/google/shaka-player/issues/359) seems to indicate that this is not the case).
