### ISSUE TITLE
TEMI timescale for transport stream

### ISSUE THREAD

**Issue by sanju-c** [gpac/gpac#1525]
We are using MP42TS to create transport stream and we have this requirement to have the timeline of different tick rate for the same fps video. By default timeline will have a tick rate equal to the frame rate . Can this be set or changed in any way?

**Comment by jeanlf** [comment]
This should now be supported in master (mp42ts is deprecated, you will have to use gpac app)

I cleanup quite a lot TEMI support in the muxer, check:
- temi2 [example](https://github.com/gpac/testsuite/blob/filters/scripts/tsmux.sh)
- TEMI [section](https://github.com/gpac/gpac/wiki/m2tsmx#time-and-external-media-information-temi) of TS muxer doc

**Comment by sanju-c** [comment]
I think those options for temi are not working, I have used below command :
gpac -i video.mp4 -i audio.mp4 m2tsmx:temi=#PV -o output.ts 
But I can see temi on both the stream, infact none of the options added are not working!!
Could you please check once

**Comment by sanju-c** [comment]
also there are options with the same character 'D for both delay and timescale

**Comment by sanju-c** [comment]
> I think those options for temi are not working, I have used below command :
> gpac -i video.mp4 -i audio.mp4 m2tsmx:temi=#PV -o output.ts
> But I can see temi on both the stream, infact **none of the options added are working**!!
> Could you please check once

Oh, I am sorry, fault from my side, I checked again with the format '#OPT1[#OPT2]#ID_OR_URL.'. Looks like it works. Thanks . But I get this warning 'No filter chain found for PID ts_mux in filter m2tsmx to any loaded filters - NOT CONNECTED' when I use this command :  "gpac -i video.mp4 -i audio.mp4 m2tsmx:temi=#PV#4 -o test_temi.ts". Should this warning be taken care in this case?

**Comment by jeanlf** [comment]
1- double 'D': Typo in doc now fixed, thanks for the report.

2- Warnings
Do not specify the muxer, just put its options on the destination filter (they are inherited by the chain):
`gpac -i video.mp4 -i audio.mp4 -o test_temi.ts:temi=#PV#4`

or specify them as global args:
`gpac -i video.mp4 -i audio.mp4 -o test_temi.ts --temi=#PV#4`


Otherwise, with your syntax, you need  have to insert a link instruction '@' between the muxer and the destination do:

`gpac -i video.mp4 -i audio.mp4 m2tsmx:temi=#PV#4 @ -o test_temi.ts`

Not specifying the link will result in loading a secondary TS muxer during the graph resolution, which will trigger the messages you have.
