### ISSUE TITLE
Automatic output to UDP

### ISSUE THREAD

**Issue by RodolpheFouquet** [gpac/gpac#1559]
Hi,

I've tried streaming a real time transcoded video (only) into a UDP stream, and it seems that when a udp url is used as output, the udp filter isn't automatically selected.

Command line used 
` gpac  -i ~/jdg.mp4:FID=1  reframer:rt=on:FID=2 ffsws:osize=128x128:SID=2:FID=EV3 @ enc:c=avc:FID=EV2 -o udp://239.10.90.75:5001:SID=EV2`

It works when I output to a file.

Am I missing something?

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment]
Which filter is used instead (use `-graph` to check the graph) ?

**Comment by jeanlf** [comment]
OK two things:

First, we had a bug when the URL was not properly setup, e.g. `-o udp://IP:PORT:opts` instead of `-o udp://IP:PORT/:opts`, both syntaxes should now work.

Second, you don't specify a mux format of the destination, and it cannot be inferred from the graph because the filter is loaded before the graph resolution. You must set either mime or extension:
-  `-o udp://239.10.90.75:5001:SID=EV2:ext=264` for raw AVC/H264 on UDP
-  `-o udp://239.10.90.75:5001:SID=EV2:ext=ts` for MPEG-2 TS 

The bug was causing a wrong parsing of extension in socket out, failing to throw an error indicating that the mux format is not specified.
