### ISSUE TITLE
[FEATURE REQUEST] Migration to Gradle/POD

### ISSUE THREAD

**Issue by Duna** [gpac/gpac#1708]
I just want to thank you for your open source project, it is awesome!

One more thing I want to add: Migrate the Android/iOS integration to Gradle/PODs. It is very **hard** to get a successful .so files and create wrappers. FFMPEG has one project with gradle integration for Android and iOS, You should do the same.

Gradle file:
```
dependencies {
    implementation 'com.arthenica:mobile-ffmpeg-full-gpl:4.4.LTS'
}
```
Same with iOS project by including PODs

**Comment by aureliendavid** [comment]
I don't think uploading to any sort of central repository is in the books for now since the android versions are very much works in progress. 

We do upload binary versions of osmo4 for android at https://gpac.wp.imt.fr/downloads/gpac-nightly-builds/ (these apks will now include libmp4box.so since it's built at the same time). Building mp4box for android from there shouldn't be too. We might also distribute binary version of mp4box for android as apks in the future but it probably will be on gpac.io and not on gradle or something similar. 

Although if we do find development resources for android and the projects acquire more maturity, I agree that it would be a good distribution option then.
