### ISSUE TITLE
when resampling audio the timescale is not updated accordingly

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#1727]
For example:
- ```gpac -i SOURCE44100#audio inspect 2>&1 | grep Timescale``` gives ```Timescale: 44100```
- ```gpac -i SOURCE44100#audio  @ resample:osr=48000 @ inspect 2>&1 | grep Timescale``` gives ```Timescale: 44100```
- ```gpac -i SOURCE44100#audio @ ffavf:f=aresample:sample_rate=48000 @ inspect 2>&1 | grep Timescale``` gives ```Timescale: 44100```

It means that when dashing, we get durations expressed in the source timescale. Is it what we want to do?

**Comment by jeanlf** [comment]
For [resample](http://wiki.gpac.io/resample) filter, this was fixed [here](https://github.com/gpac/gpac/commit/ba75191c07128f75af9245f1e22d2849c319f9c5).

For ffavf, your syntax is not correct which results in passing no args (hence identity resampler). You must use `=` as the first option delimiter after the AVF graph, not `:`, and you must escape the graph description (double `:`) - cf [ffavf](http://wiki.gpac.io/ffavf)  doc:
`gpac -i SOURCE44100#audio @ ffavf::f=aresample=sample_rate=48000 @ inspect`
 

I just fixed ffavf to report unused options due to bad filter graph specifier.
