### ISSUE TITLE
gf_filter_process_task: Assertion `filter->process_task_queued' failed.

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#1778]
Result:
```
Filter httpout request for real-time reschedule but filter is not in process
gpac: filter_core/filter.c:2349: gf_filter_process_task: Assertion `filter->process_task_queued' failed.
Abandon
```

Terminal 1: 
```
rm -rf /tmp/gpac/route1 && gpac avgen enc:c=avc:fintra=1 @ reframer:rt=on:FID=EV enc:c=aac @ reframer:rt=on:FID=EA -o http://localhost:8080/live.mpd:profile=live:dmode=dynamic:segdur=2:reqlog='*':cors=auto:rdirs=/tmp/gpac/route1:SID=EA,EV
```

Terminal 2:
```
gpac -i http://127.0.0.1:8080/live.mpd dashin:forward=file @ -o route://225.1.1.0:6000:llmode
```

Terminal 3:
```
$ rm -rf /tmp/gpac/route2 && gpac -logs=dash@info -graph -i route://225.1.1.0:6000/:max_segs=40 dashin:forward=segb:#BUrl=AAA,BBB:FID=R1 dashin:forward=file:FID=R2 -o http://127.0.0.1:8081/live.mpd:sigfrag:profile=live:dmode=dynamic:template='':segdur=2:rdirs=/tmp/gpac/route2:reqlog='*':cors=auto:SID=R1,R2
```

**Comment by rbouqueau** [comment]
I can't reproduce either because I encounter #1779 way more often. I propose to retry once #1779 is closed ; if I can't reproduce we'll close this one as well.

**Comment by rbouqueau** [comment]
I've retested  now that #1779 is closed. I now get a lot of inaccessible manifests:
```
$ gpac -play http://127.0.0.1:8081/live.mpd
Type 'h' in window for command list
[HTTP] Failure - body: Resource /audio_dash_track1_65.m4s cannot be resolved
[HTTP] Failure - body: Resource /video_dash_track2_65.m4s cannot be resolved
[DASH] Error - cannot update playlist: MPD file type is not correct /tmp/gpac_cache/gpac_cache_030759783E8316CC12F7558535CA6AAE36D48C97.mpd
[DASH] Error updating MPD BitStream Not Compliant
[DASH] Error - cannot update playlist: MPD file type is not correct /tmp/gpac_cache/gpac_cache_030759783E8316CC12F7558535CA6AAE36D48C97.mpd
[DASH] Error updating MPD BitStream Not Compliant
[DASH] Error - cannot update playlist: MPD file type is not correct /tmp/gpac_cache/gpac_cache_030759783E8316CC12F7558535CA6AAE36D48C97.mpd
[DASH] Error updating MPD BitStream Not Compliant
[DASH] Error - cannot update playlist: MPD file type is not correct /tmp/gpac_cache/gpac_cache_030759783E8316CC12F7558535CA6AAE36D48C97.mpd
[DASH] Error updating MPD BitStream Not Compliant
[DASH] Error - cannot update playlist: MPD file type is not correct /tmp/gpac_cache/gpac_cache_030759783E8316CC12F7558535CA6AAE36D48C97.mpd
[DASH] Error updating MPD BitStream Not Complia
```

No trace of the initial bug though (when it runs).

**Comment by rbouqueau** [comment]
fixed, thank you so much :)

**Comment by jeanlf** [comment]
ok the last error is due to a bogus graph specification for T3 command, I patched httpout to throw errors in such case.

Explanations (with simplified cmd line):

`gpac -i DASH dashin:forward=segb:FID=R1 dashin:forward=file:FID=R2 -o http://127.0.0.1:8081/live.mpd:sigfrag:rdirs=tmp:SID=R1,R2
`

In this case, R2 will link directly to httpout through its manifest PID, and then R1 will link to this filter invoking a mp4mx which will have no file name assigned. This was not detected properly, overwriting `live.mpd` with the mp4mx output !

What you want (I guess) is to have R1 linking to httpout as a manifest only.  The proper syntax is to list the destinations:

`gpac -i DASH dashin:forward=segb:FID=R1 dashin:forward=file:FID=R2 -o http://127.0.0.1:8081/live_rw.mpd:sigfrag:rdirs=tmp:SID=R1  -o http://127.0.0.1:8081/live.mpd:SID=R2
`

I also updated httpout doc for multi output single server examples.
