### ISSUE TITLE
Where can I get the frame data from the MPEG DASH Videos?

### ISSUE THREAD

**Issue by kjtseng** [gpac/gpac#1826]
I want to use the MPEG DASH SRD and HEVC tiling for 360 VR videos.
I have created a DASH MPD files by the guide.
Where can I get the frame data from the streamed 360 video?
I want to use shared memory to display the frame in Unity.
So that I can use the real HMD( e.g. the HTC VIVE pro ) to see the videos.
I can not find the answer from internet.
please help me.

**Comment by rbouqueau** [comment]
You're closing the issue. Do you have any useful information that might help the people having the same issue?

**Comment by lukf12** [comment]
Hello, I know this issue is long closed but I am actually working on the same idea. 
I already have gpac running together with the kvazaar encoder for tiling live 360° videos and then create a live dash session out of it. This works fine but now I am at the state where I need to present it inside a VR headset (in my case a Meta device but this does not matter) 
Maybe anyone has some news on how to represent the video on an HMD or even in Unity ? 
Thanks in advance :) 
Lukas
