### ISSUE TITLE
Where can I change the angle of the camera of the viewport?

### ISSUE THREAD

**Issue by kjtseng** [gpac/gpac#1830]
I'm using the VR360 mode.
I want to rotate the camera of the viewport by code , instead of using mouse and keyboard.

**Comment by jeanlf** [comment]
There is currently no JS bindings for that, you'll need to code them (scenejs_funcs in gpac/src/jsmods) or hack the compositor_handle_navigation function.

One other way if you know all your events up front is to use the validator module to read a trace of events and replay the trace - an example file is given [here](https://github.com/gpac/testsuite/blob/master/rules/bt-2D-interactivity-mousesensor-play-ui.xml)

Record is done using:
```MP4Client -no-save  SRC_URL -opt Validator:Mode=Record -opt Validator:Trace=FullRecPath.xml```

Playback  is done using:
```MP4Client  -no-save  SRC_URL -opt Validator:Mode=Play -opt Validator:Trace=FullRecPath.xml```

Note that this works also using `gpac`instead of `MP4Client`.
