### ISSUE TITLE
How can I measure the quality of 360 video?

### ISSUE THREAD

**Issue by kjtseng** [gpac/gpac#1835]
How can I measure the quality of 360 video? 
I 'm playing 360 Video tiled streaming which is created by the following command.
mp4box.exe -dash 1000 -frag 1000 -profile live 10M.mp4 20M.mp4 30M.mp4 40M.mp4 -out "10x10\dash.mpd"

Could it possible to measure the merged viewport?
I saw the other people measured by VMAF and PSNR. #1713
But he used a complete MP4.
Could it possible to save the mp4 when I use the MP4Client to play the DASH ?

**Comment by jeanlf** [comment]
You cannot save the resulting session as played by MP4Client easily, it will anyway require reassembly of the files.

You can try however to use the compositor as a regular filter (rather than as a sink in MP4Client) and redirect the source to a muxer at the same time:

```
gpac -i MPD_URL#VR @ compositor @ vout @@ -o dump.mp4:frag -graph
```

This should dump the content from the dash demux to file (check the graph is correct), and you should still be able to navigate in the content.

Also don't forget to use `frag` mode for record, we have a bug not flushing regular non-fragmented files for such setup, I'll investigate.
