### ISSUE TITLE
[issues] It will take about 5 seconds to switch the bit rate of dash 

### ISSUE THREAD

**Issue by xuqiqiang** [gpac/gpac#1852]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

We compile the lastest Osmo4 project and find some issues:

We load the following video: http://download.tsi.telecom-paristech.fr/gpac/SRD/tears_of_steal/tos_srd_all.mpd.
And we call this method to switch the bit rate of dash.

```
gf_dash_switch_quality(ctx->dash, GF_TRUE, GF_TRUE);
```
It will take about 5 seconds to see the effect.

And we try to seek the time by calling the following method, then It will take about 5 seconds similarly.

```
gf_dash_seek(dash, 0);
```

**Comment by jeanlf** [comment]
as of GPAC 0.9, the immediate_switch mode is deprecated (I'll update the API/doc asap), because the DASH client no longer downloads segments, this is the responsibility of its user/caller, in this case the dashin filter.  And the dashin filter logic is to keep pushing into the decoding buffer as soon as possible (buffer not full and segment ready), but it will never try to reset any already dispatched data. 
So the effect of calling `gf_dash_switch_quality` are only visible once all data in decoding buffer at the time of this call are rendered. If you want faster switch, lower the buffer time of the client.

The same applies for `gf_dash_seek`, if you call this outside of filter chain events (stop/play), you will need to purge your decoding buffers.

**Comment by xuqiqiang** [comment]
> as of GPAC 0.9, the immediate_switch mode is deprecated (I'll update the API/doc asap), because the DASH client no longer downloads segments, this is the responsibility of its user/caller, in this case the dashin filter. And the dashin filter logic is to keep pushing into the decoding buffer as soon as possible (buffer not full and segment ready), but it will never try to reset any already dispatched data.
> So the effect of calling `gf_dash_switch_quality` are only visible once all data in decoding buffer at the time of this call are rendered. If you want faster switch, lower the buffer time of the client.
> 
> The same applies for `gf_dash_seek`, if you call this outside of filter chain events (stop/play), you will need to purge your decoding buffers.

How to lower the buffer time of the client? Is it calling this method?

```
gf_dash_set_user_buffer(ctx->dash, buffer_ms);
```

**Comment by jeanlf** [comment]
It depends on your client:
- if you use gpac/MP4Client/Osmo4 for playback, this is controlled by the `buffer` and `mbuffer` options of compositor or vout
- if you use a custum client relying on a filter session and dashin, you need to setup buffer requirements at the sink (output), see for example the Python [howto example](https://github.com/gpac/gpac/wiki/python#advanced-example)
- if you only use the DASHClient object without any filter session, it's up to your client to limit the buffer and give the right info back to the DASH client, see [dashin code](https://github.com/gpac/gpac/blob/master/src/filters/dmx_dash.c#L984) for an example
