### ISSUE TITLE
Unable to clone gpac_public

### ISSUE THREAD

**Issue by dunha** [gpac/gpac#1860]
I'm building MP4Box Only on Windows and having some trouble with the git clone.
As a git noob I was unable to use the command `git clone https://github.com/gpac/gpac gpac_public` as recommended as it failed in Visual Studio 2019 and at the command line.
I suspect this is to do with the space before gpac_public, but not sure how to deal with it. What does it mean?
I was able to clone with the url [https://github.com/gpac/gpac.git](url), but the build directory was not cloned with it.

What am I doing wrong? Sorry for the noob question

I was able to build the solution very effectively by downloading the master branch, but this is not ideal from a maintenance perspective

Thanks

**Comment by rbouqueau** [comment]
Hi,

On github click on the green "Code" button to see the options. ```https://github.com/gpac/gpac.git``` is one of them. https://github.com/gpac/gpac is the github Web front-end although it seems to have worked. I've fixed in the occurrences in the doc, thanks.

> I suspect this is to do with the space before gpac_public, but not sure how to deal with it. What does it mean?

No, the element after the space is the name of the folder you're cloning into.

**Comment by dunha** [comment]
Perfect, thanks. I got the build too this time
