### ISSUE TITLE
SDL2 support instead of SDL ...

### ISSUE THREAD

**Issue by jiapei100** [gpac/gpac#1877]
- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...).

Trying to build **gpac** from source under Ubuntu 20.04 . Failed while installation:

```console
(Reading database ... 584705 files and directories currently installed.)
Preparing to unpack .../gpac/gpac_1.1.0-6_amd64.deb ...
Unpacking gpac (1.1.0-6) over (1.1.0-6) ...
dpkg: dependency problems prevent configuration of gpac:
 gpac depends on sdl; however:
  Package sdl is not installed.

dpkg: error processing package gpac (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.9.1-1) ...
Errors were encountered while processing:
 gpac
```

**Comment by aureliendavid** [comment]
did you build the .deb yourself? 

if you just want to build and install on the same machine you can just run `make install` instead of building a deb package

if you want a deb package `make deb` should work, I don't know why yours depends on `sdl`, if you look at the official builds for ubuntu 18.04 on gpac.io the dependency is on `libsdl2-2.0-0` so there's probably something in your build environment that creates this dependency, not sure

**Comment by jeanlf** [comment]
closing as it doesn't seem to be a gpac issue. Feel free to re-open and add more details if needed
