### ISSUE TITLE
When to release a new version

### ISSUE THREAD

**Issue by zrrto** [gpac/gpac#1945]
The latest version has been released for more than a year，and the master branch has added many features and fixed many bugs。Can you release a new version，so people can use these new features and test them extensively?

**Comment by aureliendavid** [comment]
Hi, 

I'm not sure when the next tagged release will be, but you can still try the latest version either by using the installers at https://gpac.wp.imt.fr/downloads/gpac-nightly-builds/ or by building the master branch by following the instructions at https://github.com/gpac/gpac/wiki/Build-Introduction

The model here is to use continuous integration and continuous delivery so that the HEAD of the master branch is always the current release. On top of that some tags are applied when a significant set of features have been added or a milestone has been reached. 

So please feel free to use the latest builds at https://gpac.wp.imt.fr/downloads/gpac-nightly-builds/ and report any issue you might encounter.

**Comment by rbouqueau** [comment]
Linux distrib maintainers asks us to make regular releases. They can't follow each repo individually. So having regular releases ease their job.

When all tests are green what would prevent us from making a release on a regular basis?

**Comment by aureliendavid** [comment]
I guess nothing is really preventing us to release more often if we chose to. 

Currently the choice is to use CI/CD for active development and tag significant advances but we could tag minor/revision versions if it's something useful (although I think this shouldn't be automated). 

Linux packages don't necessarily have to be bleeding-edge either so there's probably a good compromise somewhere in the middle.

**Comment by cindymast** [comment]
![截图](https://user-images.githubusercontent.com/47810815/142990200-59d063a5-9fa1-4d47-b025-e02165924cb2.PNG)

Notice the targets of V1.1.0。

The targets has been completed, is it possible to push the new version ？

**Comment by jeanlf** [comment]
it's planned yes, likely before end of next week
