### ISSUE TITLE
How to merge 2 (or more) existing DASH manifests

### ISSUE THREAD

**Issue by akkermansadriaan** [gpac/gpac#1954]
#### Description:
I want to merge 2 (or more) dash manifests into 1, each in a different period.

I understand this can be done using a playlist `gpac -i playlist.m3u -o manifest.mpd:sigfrag` and `sigfrag` for manifest generation only.
```
##begin pl.m3u
#props=#Period=1
asset1/manifest.mpd
#props=#Period=2
asset2/manifest.mpd
##end playlist
```
#### Expected:
All AdaptationSets & all Representations are in the new manifest.

#### Actual:
Only 1 video and 1 audio AdaptationSet/Representation is taken from the original manifests.

#### Environment:
 - macOS Monterey 12.0.1 (Apple M1)
 - GPAC version 1.1.0-DEV-rev1491-g5bed60917-master and 1.0.1 (released in September 2020) from the Downloads page

**Comment by jeanlf** [comment]
Never thought of that use case, so let's give it a try :)

Using `:sigfrag` for output manifest is OK.
 
By doing a playlist, you rebuild the timing of the source media into a continuous timeline, and this has a lot of implications: for subsequent periods, time will be different, so
- $Time indexing will be wrong
- presentation time offsets will not match first segment tfdt 
- overall period duration might slightly change if the playlist timing logic inserts a gap in one stream to maintain sync
- the bandwidth will be recomputed from input stream, which may not match the MPD bandwidth and hence break $Bandwidth templates

Furthermore, the playlist only forwards the boundaries of the segment if `:sigfrag` is set on the sources (or globally), but it will not forward any MPD-related info such as template mechanism used.

The proper way to do this is by using multiple dash inputs (will not change the timeline), each running in segment boundary forward mode [`--forward=segb`](https://github.com/gpac/gpac/wiki/dashin#segment-bound-modes), so that:
- all representations are split (this mode implies `split_as`) and played
- segment boundaries are notified (and fragment boundaries since this mode implies `:sigfrag` on sources, but fragmentation does not impact the MPD generation)
- mpd info (templates, bandwidth etc)

Since source manifests may have periodID defined, assigning a periodID can be dangerous, I think it's safer to use period start order, eg `:#PStart=-1`, `:#PStart=-2`

 
After a bit of tweaking (see 87f91f7), the following seems to work:
`gpac --forward=segb -i dash1/manifest.mpd:#PStart=-1 -i dash2/manifest.mpd:#PStart=-2 -o merged.mpd:sigfrag`


I added a few tests for that [here](https://github.com/gpac/testsuite/blob/master/scripts/dash_forward.sh#L120)

Note that the output MPD must be created in a parent folder of the input assets for this to work.

That being said, this goes a bit outside of the scope of the manifest rewrite mode and may likely not work with all possible MPD sources. There are alternatives which can be simpler or more reliable:
- text editor ;)
- using MPD chaining
