### ISSUE TITLE
Support drop tile for python API

### ISSUE THREAD

**Issue by phananh1010** [gpac/gpac#2084]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!
- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...).

Hello,

I am following example [here](https://github.com/gpac/testsuite/blob/filters/media/python/dash_bind.py) to extend the DASH algorithm. I am aware that I could change the bitrate to fit into the bandwidth conditions.
Unfortunately, I cannot find option to drop (not to download) certain tiles. 

Does the python API support dropping tiles ? Or is there any alternative?

GPAC version: version 1.1.0-DEV-rev1555-g339e7a736-master

Thank you,

**Comment by jeanlf** [comment]
If the rate adaptation algo for a group returns `-2`, that group is disabled - see [doc](https://doxygen.gpac.io/classlibgpac_1_1_d_a_s_h_custom_algorithm.html#a192df6fb7660a43e287d64f670867f71)

For example, to disable tiles that are not on left or top border every odd segment and enable them every even segment, add in the rate adaptation callback

```
group.visible = not group.visible
if not group.visible and group.SRD and group.SRD.x and group.SRD.y:
	return -2
```

Note that we had a bug reactivating the disabled group, you had to pass a different quality value than the ones used at last deactivation. This bug is now fixed on master.
