### ISSUE TITLE
Opening osmo4 in Win11 VM fails

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#2143]
[gpac-2.1-DEV-rev48-gf6d6225a-master-x64.exe](https://download.tsi.telecom-paristech.fr/gpac/new_builds/win64/gpac-2.1-DEV-rev48-gf6d6225a-master-x64.exe)

When I open osmo4, it opens a grey window and closes after a few seconds. When opening with a console I see ```[Compositor] OpenGL shaders not supported```.

**Comment by aureliendavid** [comment]
Hi, 

I ran some tests because I couldn't reproduce it either on my physical windows 11 machine, or on a windows 11 vm from https://developer.microsoft.com/fr-fr/windows/downloads/virtual-machines/

So I installed a fresh windows 11 vm from the iso, and I got the same error message. 

Turns out it comes from the video driver of the vm. The most basic and generic driver installed on a windows vm will default to open 1.1 and no extensions. We need some 3d support and opengl extensions to run mp4client, so we have to install a better graphics driver, which can be done by installing the "VMWare tools" (vmware) or the "guest additions" (virtualbox) or something equivalent. 

The display adapter of the vm should go from something like "generic microsoft graphics card" to (in my case) "VMWare SVGA 3D" and then mp4client runs correctly.

**Comment by rbouqueau** [comment]
No but now I guess it is a problem linked to my setup. I've activate opengl and 3d accel on the QEMU/KVM host side. But I've failed to install the virt io guest tools & co, that fails on my VM :(

**Comment by rbouqueau** [comment]
For the record I had followed:
- https://cpaelzer.github.io/blogs/006-mediated-device-to-pass-parts-of-your-gpu-to-a-guest/
- https://ryan.himmelwright.net/post/virtio-3d-vms/

**Comment by cglmrfreeman** [comment]
>  We need some 3d support and opengl extensions to run mp4client

What is the reason for this? That seems unreasonable to render a gui?

**Comment by jeanlf** [comment]
@cglmrfreeman you can run the client without 3D support, but chances are that video playback will be quite slow

**Comment by cglmrfreeman** [comment]
Video playback through a VM isn't going to be pretty regardless of the client you use. If rendering the data requires an OS that isn't your host, sometimes you just have to VM it up.
