### ISSUE TITLE
Can I use mp4box to set audio ID# when concat multiple video files?

### ISSUE THREAD

**Issue by zydjohnHotmail** [gpac/gpac#2185]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Let's say I have 3 video (mp4 format) files: 1.mp4, 2.mp4, 3.mp4
I can use the following command to concat them:
mp4box -force-cat -cat 1.mp4 -cat 2.mp4 -cat 3.mp4 merge.mp4
This works well.  However, when I want to extract audio from the merge.mp4 file, I have to manually use mp4box -info merge.mp4 to find what is the track ID# for audio, some times, this value is rather high, like 256 or 257.
I want to know if it is possible to set video/audio track ID when I concat multiple videos, all the videos have the same resolution and frame rate.
But I want to forecily set the audio track ID# to 2, and set video track ID# to 1.
Is it possible, if yes, please provide some command samples.
Thanks,

**Comment by jeanlf** [comment]
You can use `:ID=N` option on your source if they are single tracks, but that doesn't work if sources are multiplexed.

For export `MP4Box -raw audio merged.mp4` should do it.

That being said, most track operations are based on track IDs which can indeed be limiting. I just patched the code so that one can use IDs (e.g.`2`, numbers (e.g. `n2`) or media types (e.g. `audio` or `audio2`) in track specifiers. 

So you can now do something along:
```MP4Box -set-track-id video:1 -set-track-id audio:2 merged.mp4```
