### ISSUE TITLE
I want to ask some questions about python api

### ISSUE THREAD

**Issue by a23232390** [gpac/gpac#2224]
![image](https://user-images.githubusercontent.com/68137277/178431338-a8f57637-ddc3-43cd-85f4-05c9967fe0eb.png)
this picture gpac -gui url
in the picture the BW is python api(self.download_rate ) right?
and all tiles needed bandwidth is python api (self.total_rate) right?

**Comment by jeanlf** [comment]
> in the picture the BW is python api(self.download_rate ) right?

not exactly, BW plot in gui is the estimated global download rate for all active http connections, it matches python [session.http_bitrate](https://doxygen.gpac.io/classpython_1_1libgpac_1_1libgpac_1_1_filter_session.html#a31223012cba8ee5207e7556a60dce1cc)

The python [download_rate](https://doxygen.gpac.io/classpython_1_1libgpac_1_1libgpac_1_1_d_a_s_h_group_statistics.html#a222ac1835b69d184ed5432ddf866c273) is the download rate of the last segment for the given dash group, which can be higher than the global rate

> and all tiles needed bandwidth is python api (self.total_rate) right?

No, self.total_rate is the cumulated download rate of the last downloaded segment of each active group in the dash client - the required bandwidth for all active groups is not exposed since qualities are usually picked by the python algo. Available qualities per group are exposed through the [DASHQualityInfo](https://doxygen.gpac.io/classpython_1_1libgpac_1_1libgpac_1_1_d_a_s_h_quality_info.html)

**Comment by a23232390** [comment]
Excuse me, I want to ask how to call [session.http_bitrate](https://doxygen.gpac.io/classpython_1_1libgpac_1_1libgpac_1_1_filter_session.html#a31223012cba8ee5207e7556a60dce1cc) on python code 
I am referring Advanced example (https://github.com/gpac/gpac/wiki/python#advanced-example)
