### ISSUE TITLE
Introduction of bsrw filter breaks execution

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#2269]
```gpac -i avgen:dur=2  @ c=h264 -o gpac.mp4``` works but ```gpac -i avgen:dur=2  @ c=h264 @ bsrw -o gpac.mp4``` loops forever.

**Comment by jeanlf** [comment]
> gpac -i avgen:dur=2 @ c=h264 -o gpac.mp4 works 

no it doesn't: "No filter chain found for PID video in filter rfnalu to any loaded filters - NOT CONNECTED"

This is because your link directive allows avgen->mp4 connection, and the ffenc->mp4 later fails since due to a cyclic input to mp4mx detected - I'll see if I can lift a bit this constraint here.

But `gpac -i avgen:dur=2 c=h264 -o gpac.mp4` works (the implicit linking will connect video only to the encoder).

> gpac -i avgen:dur=2 @ c=h264 @ bsrw -o gpac.mp4 loops forever

Indeed, because now the cycle is not detected due to the explicit filter (bsrw here), and we end up with raw video and encoded video from the same source (avgen) entering the mux. Since avgen video is dispatched as reference packets and x264 needs several frames before outputting, this was causing a deadlock of the muxer trying to figure out initial sync of streams, now fixed.

again using `gpac -i avgen:dur=2 c=h264 bsrw -o gpac.mp4` works as expected, the implicit linking will connect:
- video  to the encoder only
- encoder to bsrw, audio to bsrw
- audio to bsrw
- bsrw to mp4, resulting in raw audio and avc video in final output.

**Comment by rbouqueau** [comment]
Thanks for the fix and the explanation. However imagine I want to process video-only from my source (e.g. avgen), how do I do?

**Comment by jeanlf** [comment]
if you only need video from avgen, `avgen:v` (<=> `avgen:type=v`)

if you want raw audio and compressed video:

`gpac -i avgen:dur=2 c=h264 -o gpac.mp4`

if you want raw audio and compressed video + bsrw filter on video only:

`gpac -i avgen:dur=2 c=h264 @ bsrw @ @@0#audio -o gpac.mp4`

NOTE: we currently have a limitation in the resolver, using `gpac -i avgen:dur=2 c=h264 @ bsrw -o gpac.mp4` will make the encoder output connected to both the muxer and bsrw, I'll look into this.

Since bsrw is passthrough if nothing needs to be rewritten, you can also just use:

`gpac -i avgen:dur=2 c=h264 bsrw -o gpac.mp4`

**Comment by jeanlf** [comment]
`gpac -i avgen:dur=2 c=h264 @ bsrw -o gpac.mp4` is now working as expected for implicit link mode
