### ISSUE TITLE
command-line never exits

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#2270]
When putting some wrong parameters (hevc with avc options), my command-line stalled:

```
gpac -i avgen:dur=2  @ enc:gfloc:c=hevc:b=5100k:r=30/1:bf=2:b_strategy=0:fintra=2:profile=high:color_primaries=1:color_trc=1:colorspace=1::x264-params="level=40:no-open-gop=1:scenecut=0" -o hevc.mp4
```

**Comment by jeanlf** [comment]
again the culprit is the '@', resulting in avgen video pid linked to both the encoder and the output. The failure of the encoder was triggering a discard on all avgen video pid destinations, now fixed.

I also added a fail-safe to the isom muxer to abort timing config if no packet seen after a while.
