### ISSUE TITLE
Potential memory leak in src/filters/ff_dmx.c

### ISSUE THREAD

**Issue by icy17** [gpac/gpac#2382]
Potential memory leak in [ff_dmx.c](https://github.com/gpac/gpac/blob/master/src/filters/ff_dmx.c) line 1728 and 1736. Calling av_dict_set()  without calling av_dict_free() to free the memory will cause a memory leak. [Doc](https://ffmpeg.org/doxygen/trunk/group__lavu__dict.html#ga1bafd682b1fbb90e48a4cc3814b820f7) says "av_dict_free() Free all the memory allocated for an [AVDictionary](https://ffmpeg.org/doxygen/trunk/structAVDictionary.html) struct and all keys and values."
![image](https://user-images.githubusercontent.com/39425646/214519771-6f562018-702e-41ce-b83e-e5b4c0c0c158.png)

**Comment by aureliendavid** [comment]
Hi, 

Thanks for the report. 

It's true that these dicts should be freed (in practice it probably doesn't leak because the functions that use the dicts will free them and reallocate dicts containing options that are not found if there are any - here if the list_devices option exist then there is not leak)

but still it should fixed in the above commit 

reopen if needed
