### ISSUE TITLE
[MP4Box] The movie and the track durations are not shown

### ISSUE THREAD

**Issue by vladimir-kazakov** [gpac/gpac#253]
Hi!

In #234, one issue with MP4Box was detected: https://github.com/gpac/gpac/issues/234#issuecomment-139476108.

The media can be found here: http://1drv.ms/1JPg0t8 (in the eDash folder).

So, the problem is that when using the `mp4box.exe -info`, it shows that the movie duration and the track duration are zeroes, although the media itself contains non-zero information. For example, this is what MP4Box shows (see: /eDash/mp4box.info.video.txt):
```
* Movie Info *
        Timescale 12288 - Duration 00:00:00.000
        1 track(s)
        Fragmented File: yes - duration 00:00:52.208
27 fragments - 1 SegmentIndexes
        File suitable for progressive download (moov before mdat)
        File Brand dash - version 0
        Created: GMT Tue Sep 08 11:00:56 2015
        Modified: GMT Tue Sep 08 11:00:56 2015

File has no MPEG4 IOD/OD

Track # 1 Info - TrackID 1 - TimeScale 12288 - Media Duration 00:00:00.000
Media Info: Language "und (und)" - Type "vide:avc1" - 0 samples
Fragmented track: 1253 samples - Media Duration 00:00:52.208
Visual Track layout: x=0 y=0 width=640 height=360
MPEG-4 Config: Visual Stream - ObjectTypeIndication 0x21
AVC/H264 Video - Visual Size 640 x 360
        AVC Info: 1 SPS - 1 PPS - Profile High @ Level 3
        NAL Unit length bits: 32
        Pixel Aspect Ratio 1:1 - Indicated track size 640 x 360
        SPS#1 hash: 4CB56C454FE3B93E30D7D2B6425805D02E55BD2D
        PPS#1 hash: F84447EBF61570BBEE3F9F184A7A189EAA14289D
Self-synchronized
        RFC6381 Codec Parameters: avc1.64001e
        No sync sample found
```

And that's what the media contains (see: /eDash/mp4dump.video.txt):
```javascript
{
    "name":"mvhd",
    "header_size":12,
    "size":108,
    "timescale":12288,
    "duration":641536,
    "duration(ms)":52208
}
```
```javascript
{
    "name":"tkhd",
    "header_size":12,
    "size":92,
    "enabled":1,
    "id":1,
    "duration":641536,
    "width":640.000000,
    "height":360.000000
}
```

Expected behavior: MP4Box must show correct durations.

**Comment by cconcolato** [comment]
I finally understood your problem. Indeed MP4Box reports 0 while the actual values in the `mvhd` and `tkhd` boxes are not zeros. However, the file is invalid ! The `stsc`, `stco`, `stts` and `stsz` contain no samples, so the durations should be 0. The durations that MP4Box displays is the actual computation of the duration, not the coded values. We should probably issue a warning that the file is invalid, but I'm not sure we should report the actual coded duration, as it might be misleading because if you try to play the file by a reader that does not implement fragments, it will play for 0 seconds.

**Comment by jeanlf** [comment]
this should now be fixed, MP4Box now dumps both information
