### ISSUE TITLE
rfimg filter fails at decoding most of j2k files format

### ISSUE THREAD

**Issue by gorinje** [gpac/gpac#2561]
Altough ffdmx handle most of j2k files well using j2kdec filter, same decoding with rfimg -- instead of ffdmx -- causes a crash on line 564 of   dec_j2k.c (opj_image_destroy(image);).

You will find enclosed an example of a j2k file format where the given command line : 
./gpac -i  Bretagne1.j2k -o test.png

provokes a Segmentation fault (core dumped)

The filters connected are:
rfimg (src=Bretagne1.j2k) (idx=1)
-(PID video1) j2kdec (dyn_idx=3)
--(PID video1) pngenc "encpng:1.6.39" (dyn_idx=4)
---(PID video1) writegen (dyn_idx=5)
----(PID video1) fout (dst=test.png) (idx=2)

[Bretagne1.zip](https://github.com/gpac/gpac/files/12360566/Bretagne1.zip)

**Comment by aureliendavid** [comment]
Hi, 

thanks for the report

I could reproduce a crash but not exactly in the same place as yours, so if you can retest with the above commit please confirm if it works for you or not. 

In my case the issue comes from the fact that the `rfimg` filter accepts both `jp2` (jpeg2000 isomedia-like container) and `j2k` (jpeg2000 codestream) files, but when scanning for the basic dimensions of the image we only handled the jp2 format. 

I added some basic code to handle j2k, it seems to work for me on your image. 

(if the code is not sufficient for the general case we could also just disable j2k support in rfimg and force using jp2 files).

**Comment by gorinje** [comment]
Hi,

Your modifications works perfectly on my j2k testing files, many thanks for your prompt response!

Best
