### ISSUE TITLE
Question: `master` branch does not contain `v2.2.1`

### ISSUE THREAD

**Issue by allanlei** [gpac/gpac#2660]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/bug-reporting/

---

Is it expected that the [master](https://github.com/gpac/gpac/tree/master) branch does not include the changes from [v2.2.1](https://github.com/gpac/gpac/tree/v2.2.1)?

https://github.com/gpac/gpac/compare/master...v2.2.1

**Comment by aureliendavid** [comment]
Hi, 

It's a good question because the commit history for v2.2.1 is a bit awkward. 

Short answer: master **does** contain everything form v2.2.1

Longer answer: 

v2.2 was released as a standard release. Then development continued on master as usual. Theses developments included both security fixes from opened issues, and new features to be included in the next release. (v2.3) 

However,  while waiting for the next release to be ready, some people asked us for a security release that would contain only the patches relating to opened CVEs (security patches). 

So we back-ported the security patches to a new branch called [release-2.2](https://github.com/gpac/gpac/commits/release-2.2) by git cherry-picking the relevant commits from master, and then tagged the tip of that branch as [v2.2.1](https://github.com/gpac/gpac/tree/v2.2.1)

But since they are back-ports / cherry-picks, the commit ids are different, that's why the github ui doesn't show them as being present in both master and 2.2.1. 

If you look at the [commits in 2.2.1](https://github.com/gpac/gpac/commits/release-2.2) you can find the corresponding commits in master by checking relevant issue. 

e.g. a82810c24 in 2.2.1 is the same as af6a5e7a96 in master and both fix issue #2366


To sum-up: 
- release 2.2.1 = release 2.2 + backported security fixes from master
- master = release 2.2 + security fixes + new developments (soon to be release 2.3) 


Hope this helps.
