### ISSUE TITLE
"mp4box.exe has stopped working" popup

### ISSUE THREAD

**Issue by pm1315** [gpac/gpac#269]
I have Windows 10 64-bit and am using 64-bit builds of mp4box

Builds after rev673 pop up error box with the message "mp4box.exe has stopped working"
when extracting video from an mp4 file. I'm wondering if this has to do with the reduced file size
of mp4box.exe.  In rev673 the file size of mp4box.exe was ~512kb, while in the newer revisions
the file size of mp4box.exe is ~111kb.  Is an extra support file required, or a different version of
the mscvcr runtime dll?  Thanks.

**Comment by rbouqueau** [comment]
Hi, everything seems fine here with the latest installer (0.5.2-DEV-rev703).

If the issue is still here with the latest version, please share a file and a command-line (here is an anonymous drop box, please put the issue number in the description: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95)

**Comment by pm1315** [comment]
I use a batch file that I drag & drop the mp4 file onto:

@ECHO OFF
:Begin
  IF %1.==. GOTO Error
SET mp4name="%~n1"
"C:\Program Files\mp4box\MP4Box.exe" -raw 1 %mp4name%.mp4 -out %mp4name%_vid.h264

Also, I don't run the installer, but instead use 7-Zip to extract mp4box.exe and the five required
support files (js.dll,libeay32.dll,libgpac.dll,sseay32.dll,msvcr100.dll)

Again, rev673 and before work without issue.  Later versions generate the error box
"mp4box.exe has stopped working".

Thanks.

**Comment by pm1315** [comment]
Sorry, I closed this by mistake after last comment

**Comment by rbouqueau** [comment]
It should be good now, thanks for reporting :)
