### ISSUE TITLE
Question: how to create single-segment fMP4 container output.

### ISSUE THREAD

**Issue by Canta** [gpac/gpac#2730]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: https://gpac.io/bug-reporting/

--------------------

Hi all.
I'm working with 24/7 live streams, and trying to create a fMP4 segment from _another_ segment in _another_ format. The most common case would be to just encapsulate an existing webvtt file inside a non-yet-existing m4s/mp4 container file, but could actually be other formats as well (TTML maybe, or even TS). And that part works great by simply doing something like this:

`gpac -i segment_12345.vtt -o segment_12345.m4s`

However, I understand that file is actually not fMP4 but a full MP4 container for the original content. fMP4 requires also the init file with splitted data from the full container. And I didn't found a way to create it with the docs, neither for the command line tools or the Python bindings (which I would like to use).

I understand `dasher` filter allows me to create fMP4 output, but I was unable to do it with a single webvtt file as input. And the `mp4mx` filter (which I understand is the one instanced from that example command before) doesn't seem to have any fMP4 option. Of course I've tried other options I could find in the docs, but all without success so far.

So, I decided to just ask you people: *is there a way to create single-segment fMP4 output, init file included, from mp4-compatible input, using gpac?*

Thanks in advance.

**Comment by jeanlf** [comment]
you will need to force fragmentation to a large value and skip the init segment generation:

`gpac -i segment_12345.vtt -o segment_12345.m4s:frag:cdur=10000:noinit`

it's likely that you will need to disable fragment defaults (`:nofragdef`option) in this case, as different segments may result in different defaults for rap or duration.

In order to produce the init segment, do (once, preferably with `:nofragdef`)

`gpac -i segment_12345.vtt -o dash.mpd`

and grab the init segment.

You can also add `:cmaf` option for CMAF comaptibility
