### ISSUE TITLE
How to build GPAC android edition in Windows system 

### ISSUE THREAD

**Issue by YueCrystalJin** [gpac/gpac#275]
I am trying to build the GPAC android edition in Windows system. However, according to the build/android/readme file, the command lines are not suitable to windows system. Could you help to solve the problem? Thanks.

**Comment by nguyen-viet-thanh-trung** [comment]
Hi,

For compiling Android in Windows you need to install Cygwin. Perhaps you will have some errors like '\r': command not found due to Windows style newline characters, dos2unix can resolve this problem.
Get the latest gpac_extra_libs from here: http://download.tsi.telecom-paristech.fr/gpac/gpac_extra_libs.zip

**Comment by nguyen-viet-thanh-trung** [comment]
Please reopen if you need more help !

**Comment by azhar5678** [comment]
hello ia having problem in compiling and making apk on windows through cygwin
