### ISSUE TITLE
Is it possible to set forced subtitles WebVTT (wvtt) in .mp4?

### ISSUE THREAD

**Issue by zablockil** [gpac/gpac#2770]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: https://gpac.io/bug-reporting/

----

I am testing muxing text subtitles to .mp4. It seems that forced subtitles work only in tx3g format (and correctly display in MPC-HC, VLC). I use the following commands:

"Timed Text (tx3g)" 3 .srt files
```
mp4box.exe -add "video.264#video:name=" -add "audio.aac#audio:group=1:name=" -add "srt/SUB1.srt:hdlr=text:txtflags=0xC0000000:group=2:lang=eng:name=" -add "srt/SUB2.srt:hdlr=text:group=2:disable:lang=ger:name=" -add "srt/SUB3.srt:hdlr=text:group=2:disable:lang=fre:name=" -itags reset -tmp tmp -new tx3g_from_3_srt.mp4
```

"WebVTT (wvtt)" 3 .vtt files
```
mp4box.exe -add "video.264#video:name=" -add "audio.aac#audio:group=1:name=" -add "vtt/SUB1.vtt:hdlr=text:txtflags=0xC0000000:group=2:lang=eng:name=" -add "vtt/SUB2.vtt:hdlr=text:group=2:disable:lang=ger:name=" -add "vtt/SUB3.vtt:hdlr=text:group=2:disable:lang=fre:name=" -itags reset -tmp tmp -new wvtt_from_3_vtt.mp4
```

MediaInfo:

```
Complete name               : tx3g_from_3_srt.mp4
...
Text #1
ID                          : 3
Format                      : Timed Text
Codec ID                    : tx3g
Duration                    : 1 min 29 s
Bit rate mode               : Variable
Bit rate                    : 30 b/s
Frame rate                  : 0.212 FPS
Stream size                 : 333 Bytes (0%)
Language                    : English
Default                     : Yes
Forced                      : Yes
Alternate group             : 2
```

```
Complete name               : wvtt_from_3_vtt.mp4
...
Text #1
ID                          : 3
Format                      : wvtt
Codec ID                    : wvtt
Duration                    : 1 min 29 s
Bit rate mode               : Variable
Bit rate                    : 55 b/s
Frame rate                  : 0.201 FPS
Stream size                 : 617 Bytes (0%)
Language                    : English
Default                     : Yes
Forced                      : No
Alternate group             : 2
```

I have posted the [detailed steps and test files here](https://github.com/zablockil/srt_vtt_mp4). `mp4/wvtt_from_3_vtt.mp4` file.

tested:
```
MP4Box - GPAC version 2.3-DEV-rev942-g11c9f998-master
MP4Box - GPAC version 2.3-DEV-rev911-g13a18c3f-master
```

**Comment by NeedsMoar** [comment]
Webvtt is usually used embedded on web pages with the CSS data.  I don't know how or why VLC is displaying any of the examples you've got correctly unless it's just falling back on SRT compatibility.   Most of the styling needs to be handled in CSS blocks...  aside from that though, txtflags just doesn't do anything unless used as the manual specifies (txtflags+=0x... / txtflags-=0x....).  Try setting it to 0x0 and you'll still get the same flags on both of those file types.   

Apple's docs suggest that "forced" is poorly supported by even compliant players and the better combination of flags is AUTO_SELECT + DEFAULT which does basically the same thing.  Of course, everything they make is non-compliant and their days of actually being high end video systems ended over a decade ago, so it's questionable whether they should be trusted on that at all.    Also, vtt tracks need to be flagged as subtitles or captions in order to be flagged as text since they can contain a bunch of other arbitrary metadata that isn't meant for display...  yours seems to be registering as data.   Of course every media info viewer in the known universe interprets basic header information differently and I'm not getting out a hex editor so who knows, really.

**Comment by jeanlf** [comment]
Unfortunately no, carriage of webVTT in ISOBMFF does not provide for a forced option (neither for TTML at container level).

If we manage to get this adopted, I'll add support for this.
