### ISSUE TITLE
Formatting of some arguments' help

### ISSUE THREAD

**Issue by DenizUgur** [gpac/gpac#2771]
- There are some filters' arguments whose enum values are shown as commas (`,`) instead of bar (`|`). This comes from `constants.h`. I've tried to change it but it broke something else and I cannot find what is affected by this.
- Some enum values are also listed as `uint` but actually they are string. In the code this `uint` is used as index to get the proper value. Wouldn't make more sense to convert these to `str` type?

I've listed the affected filters in the attached JSONs.
[uints.json](https://github.com/gpac/gpac/files/14488390/uints.json)
[comma.json](https://github.com/gpac/gpac/files/14488393/comma.json)

**Comment by jeanlf** [comment]
> Some enum values are also listed as uint but actually they are string. In the code this uint is used as index to get the proper value. Wouldn't make more sense to convert these to str type?

No, enums are uint however they are expressed as strings in the command line (just like every other type number/fraction/etc) . On the other hand, the `str` type is an opaque uff8 string not parsed/checked when loading options.

> There are some filters' arguments whose enum values are shown as commas (,) instead of bar (|).

Yes, because most of them  are not strict enums, they allow any names + some reserved names (cf logs)

The pixel format, audio format and audio layout could be converted to enum, but currently their type is not an `uint` so the usage of `,` instead of `|` shouldn't be an issue. 

Could you detail more how this is problematic for your use case(s) ?

**Comment by DenizUgur** [comment]
It's not really a deal breaker, I just thought there might be some oversight but apperantly everything was well thought.

For non-strict sums, are they signalled with a flag?

**Comment by DenizUgur** [comment]
For example, probe's log argument. It's an enum but it's not bound to enum values. Should I just use enum values as suggestions for `str` type arguments?

> Also, probe's log argument's enum values are separated with both comma and "or"

**Comment by jeanlf** [comment]
I did a cleanup pass, now all options using enum-like types (including pix fmts & co) will use `|`as a separator.

For mixed values like inspect.log, the convention is that "_any" should be used to indicate free string.
