### ISSUE TITLE
Is it possible to patch a segment with no init?

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#2819]
@dsilhavy reported on the video-dev slack a use-case where:
1. He wants to remove the 'uuid' box from a segment.
2. The 'uuid' box is reported by GPAC as an error anyway (the segment looks like some smooth streaming):

```
[iso file isomedia/box_code_base.c:6529] extra box uuid found in traf, deleting
[iso file] Movie fragment but no moov (yet) - possibly broken parsing!
[iso file] Error: moov not received before merging fragment
Error opening file video-2800000-42835577159.m4s: Invalid IsoMedia File
```

Is boxpatch supposed to work in this case?

**Comment by dsilhavy** [comment]
Thanks for opening this issue @rbouqueau. For means of completion, here is a zip file including the init and the media segment. Both are coming from a DASH content.

[init+video.zip](https://github.com/gpac/gpac/files/15159714/init%2Bvideo.zip)

**Comment by jeanlf** [comment]
We cannot box patch fragments files directly, we need to remux them. For your use case since it looks like piff:

```
gpac --initseg=video-2800000-init.mp4 -i video-2800000-42835577159.m4s:norw -o refrag.m4s:noinit:cdur=10000000:frag:cmf2
```

explanations:
`--initseg`: set the init segment
`mp4dmx.norw`: do not extract inband param sets (just added this one on master)
`mp4mx.noinit`: do not write init segment (moov)
`mp4mx.cdur`: set to a very large value to force producing a single fragment. Reproducing the fragmentation pattern is trickier, it requires using mp4dmx.sigfrag
`mp4mx.cmf2` to enforce piff constraints (single traf, default flags in fragments, box order, etc)

Once you have this you can start using box patches on the muxer. Although for your specific example, there is no need as the extra uuid is trashed at parsing time.

If you need to copy over unknown boxes in the source fragment, you must use `mp4dmx.sigfrag`.
