### ISSUE TITLE
AVGEN : Font error

### ISSUE THREAD

**Issue by j3dd4h** [gpac/gpac#2867]
Command:
docker run -it gpac/ubuntu:latest  gpac -rescan-fonts avgen:sizes=1280x720:rates=1300k:dyn=false c=aac:b=128k  c=avc:b=1300k  reframer:rt=on  -o out.ts

[avgen] Error processing
[avgen] Error: Fonts not found (first was SANS) and no default font available!
Check your GPAC configuration, or use `-rescan-fonts` to refresh font directory.

    at draw_view (/usr/share/gpac/scripts/jsf/avgen/init.js:709)
    at process_video (/usr/share/gpac/scripts/jsf/avgen/init.js:550)
    at <anonymous> (/usr/share/gpac/scripts/jsf/avgen/init.js:404)

It seem there is incompatible fonts.
Installing package fonts-dejavu ( apt install fonts-dejavu ) solved the problem.

**Comment by aureliendavid** [comment]
Hi, 

We've seen this before (in #2814 for example) and every time we have a lot of trouble reproducing it. 

Even here with the same docker image, testing on 3 different systems, I don't have the bug on 2 of them, but I finally have 1 where the bug reliably happens so I could do some debugging. 

It appears more often on systems that don't have many fonts installed (so a docker image or a fresh install). 

When we rescan fonts, we enumerate the fonts directory and use the first one we find as a default font, to use when no other font has been specified. 

But there's an issue if the default font is a bold or an italic font. When we try to load a regular font later it fails. (there might be something to do here to force loading what we have instead of failing, see around https://github.com/gpac/gpac/blob/master/modules/ft_font/ft_font.c#L572 for future reference). 

Now the big source of randomness which made this hard to reproduce is that directory enumeration has no guaranteed order. So a bold font might come first or it might not. Even with the exact same docker image, installed packages, etc.. 

Anyway I fixed it by overwriting the default with a regular font if we can. 

I haven't completely removed the possibility of having a bold font as default in case we have a weird system where only a bold font is available. But it is to be determined if we want to debug this case further to make it work with a bold default. 

However the fix should be enough to remove all the avgen font errors we've been seeing.
