### ISSUE TITLE
Reassemble packets into a new MP4 file

### ISSUE THREAD

**Issue by alanccw** [gpac/gpac#2975]
I have many MP4 files which are truncated in their tails, which make them not playable. I analyze these files manually and find the ftyp and moov boxes and their child boxes are all OK. But part of the data in mdat box are lost, which corresponding to some packet data only, which is <= 5% of the total packets.

So I wrote a small app that can parse all the data in the MP4 and read all the meta info from the boxes(except for mdat box), and get all the existing packets and save them as separate .dat files. Now I want to reassemble them back into a valid MP4 file.

Can I implement that with your MP4Box? I have tried ffmpeg commandline and API but failed.

**Comment by jeanlf** [comment]
The raw sample extracted might not be a valid raw bitstream format as there could be changes due to internal representation in ISOBMF (e.g. NALU start codes are replaced with fixed)length prefix size). Re-parsing it is likely not going to work

The simplest way to do what you want using GPAC is:
```
MP4Box -add truncated.mp4 -new remux.mp4
echo 'res: $?'

or

gpac -i truncated.mp4 -o remux.mp4
echo 'res: $?'

```

Both MP4Box and gpac will generate log errors when processing truncated files, but they will still produce a valid output.

If you want more control over what you want to include from each truncated file, you can use the [nhml format](https://wiki.gpac.io/xmlformats/NHML-Format/)
