### ISSUE TITLE
dependency problems prevent configuration of gpac - Debian

### ISSUE THREAD

**Issue by DrakeSeven** [gpac/gpac#3009]
Dependency Problems on `Debian GNU/Linux 12 (bookworm)`:
```bash
sudo dpkg -i gpac_latest_head_linux64.deb
```
```bash
dpkg: dependency problems prevent configuration of gpac:
 gpac depends on libavcodec58 (>= 7:4.4); however:
  Package libavcodec58 is not installed.
 gpac depends on libavdevice58 (>= 7:4.4); however:
  Package libavdevice58 is not installed.
 gpac depends on libavfilter7 (>= 7:4.4); however:
  Package libavfilter7 is not installed.
 gpac depends on libavformat58 (>= 7:4.4); however:
  Package libavformat58 is not installed.
 gpac depends on libavutil56 (>= 7:4.4); however:
  Package libavutil56 is not installed.
 gpac depends on libswscale5 (>= 7:4.4); however:
  Package libswscale5 is not installed.
```
To Fix this:
1. Remove GPAC:
    ```bash
    sudo apt remove gpac
    sudo apt autoremove
    ```
2. Enable the necessary repositories and install the dependencies:

    Add the `deb-multimedia` repository key:

    ```bash
    sudo apt install wget
    sudo wget https://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb
    sudo dpkg -i deb-multimedia-keyring_2016.8.1_all.deb
    ```

    Add the repository to the source list:

    ```bash
    sudo sh -c "echo 'deb http://www.deb-multimedia.org bookworm main non-free' >> /etc/apt/sources.list"
    ```
    _If you’re using a different Debian release, replace bookworm with the appropriate codename (e.g., `bullseye` for Debian 11)._

    Update the package list:

    ```bash
    sudo apt update
    ```

    Install the required packages:

    ```bash
    sudo apt install libavcodec58 libavdevice58 libavfilter7 libavformat58 libavutil56 libswscale5
    ```

    Install the .deb again:

    ```bash
    sudo dpkg -i gpac_latest_head_linux64.deb
    ```

**Comment by aureliendavid** [comment]
Hi, 

Thanks for the report. 

Unfortunately deb packages are not generic. As mentioned on https://gpac.io/downloads/gpac-nightly-builds/#release-installers the deb packages we build for linux64 are built on ubuntu 22.04 LTS and are only guaranteed to install on this version (it should switch to 24.04 lts soon). 

Since debian and ubuntu packages are very close, it kinda works on debian but the package versions might cause issues (e.g.: debian stable uses libavcodec59 instead of 58). 

For other distros/versions than the one the package is built on, it is recommended to build gpac from source (see https://wiki.gpac.io/Build/build/GPAC-Build-Guide-for-Linux/ ). 

If you're using the deb-multimedia repo, they also provide a gpac package (but it won't be the latest git version). 

Also when installing deb packages, instead of dpkg you can use 

```
sudo apt install ./package.deb
```

and apt will try to install the package dependencies if it can find them.

**Comment by DrakeSeven** [comment]
Thank's for the clarification!
