### ISSUE TITLE
gpac rev-727 built from sources doesn't work on Android 5.1

### ISSUE THREAD

**Issue by ghost** [gpac/gpac#302]
Hello.
I get gpac revision-727 and tried to build version for Android from original sources.
The build command used is "./gpac_build_android -ndk=/opt/android_ndk -sdk=/opt/android_sdk -ant=/usr/bin/ant -force_rebuild". The target used by default is 18 API, however, I test it on Nexus 6, Android 5.1.1.
In the end of building process I got the error "zipalign: error while loading shared libraries: libc++.so: cannot open shared object file: No such file or directory", but the build is successful, I mean I can find /gpac/applications/osmo4_android/bin/Osmo4-release.apk file.
When I open it, I got several errors:
"Error
[Core] Cannot load module file /data/data/com.gpac.Osmo4/lib//libgm_ffmpeg_in.so, error is dlopen failed: cannot locate symbol "_ZN7android16MediaBufferGroup14acquire_bufferEPPNS_11MediaBufferE" referenced by "libavcodec.so"...
"Error
[Core] Cannot load library libgm_ffmepg_in.so"
"Error
[Terminal] Did not find any input plugin for URL /data/data/com.gpac.Osmo4/gui/extensions/bifs_tests/ (no mime type)"
Then I tried to open .mpd (DASH) file and errors:
"Error
[Codec] ODM1 ES1: Cannot find decoder for stream type MPEG-4 AVC|H264 Video"

Just in case I tried to test this apk in Genymotion.
With Nexus 4 - 4.3 - API 18 Osmo4 gives me next error just on start:
"Error
[Terminal Did not find any input plugin for URL /data/data/com.gpac.Osmo4/gui/extensions/bifs_tests/ (no mime type)"
However, when I open .mpd (DASH) file, the video works well.

With Nexus 6 - 5.1.0 - API 22 Osmo4 gives the same error as in previous case, but the video doesn't work.

How can I make it works on real Android devices? For beginning, at least on Nexus 6 with Android 5.1.0.

**Comment by nguyen-viet-thanh-trung** [comment]
Hello,

Does the nightly build version work with you: https://gpac.wp.mines-telecom.fr/downloads/gpac-nightly-builds/ (perhaps you need to delete your old GPAC.cfg for testing)

From your info, it seems that you have some probleme with stagefright.

**Comment by arevi** [comment]
Yes, the night build works well. But need to build it from sources.

**Comment by arevi** [comment]
Forget to mention, ubuntu 14.04 is used for building.

**Comment by fcsteagu** [comment]
indeed Nguyen is right, the problem is libstagefright which is not for Android 5 by default. You need to rebuild gpac_extra_libs and in build/android/ffmpeg_patch/build_libstragefrigth you need to point to the right android libraries for the android version you want to use. You need to modify this line:

__wget http://download.cyanogenmod.org/get/jenkins/42509/cm-10.1.3-i9305.zip -P../__

**Comment by nguyen-viet-thanh-trung** [comment]
Well, stagefright is not stable, it depends really on your device.
For the error of zipalign, libc++ is not found. Could you try to install it ? Or, did you use a 32-bit Android SDK and your OS is 64 bits ?

**Comment by arevi** [comment]
OS is Ubuntu 14.04.3 64 bit, NDK is r10e-rc4 (64-bit), about sdk - it seems like there is not choice of 32 or 64 bit.

Where is this line locate "wget http://download.cyanogenmod.org/get/jenkins/42509/cm-10.1.3-i9305.zip -P../" ? In /gpac_extra_libs/build/android/ffmpeg_patch?
Why the default line is "wget http://download.cyanogenmod.org/get/jenkins/65493/cm-10.2.1.3-serranoltexx.zip -P../"?

Do you know, which exactly package do I need for libc++? The "libc++" gives many conflict errors.

**Comment by nguyen-viet-thanh-trung** [comment]
Hello Arevi,
Do you need support stagefright for your app ? If not, you can comment this line in build/android/gpac_build_all_extra_libs:  ./compile_ffmpeg_libstagefright_android.sh $1 || exit 1
Also, comment the script for building stagefright version in gpac/build/android/jni/gpac_build_android from line 192 (echo -e "\nBuiding Osmo4.apk (support libstagefright)" ) to line 218 (echo -e "\n[OK] success.").

It should work with you. FYI, we are now working for a more stable version support stagefright. We will tell you asap.

**Comment by arevi** [comment]
What about the line in "/gpac_extra_libs/build/android/ffmpeg_patch"? Do I need to change it to http://download.cyanogenmod.org/get/jenkins/42509/cm-10.1.3-i9305.zip ?

**Comment by nguyen-viet-thanh-trung** [comment]
No, this script is to build stagefright support

**Comment by fcsteagu** [comment]
can you please confirm that the extra libs for GPAC are the ones from here:
http://sourceforge.net/p/gpac/code/HEAD/tree/trunk/gpac_extra_libs/gpac_extra_libs.zip ?

Thanks!

**Comment by arevi** [comment]
nguyen-viet-thanh-trung, there is no line "./compile_ffmpeg_libstagefright_android.sh $1 || exit 1" in "build/android/gpac_build_all_extra_libs".
May be you meant in "compile_ffmpeg_android.sh" the line "./build_libstagefright || exit 1"?

**Comment by fcsteagu** [comment]
indeed, I have the same problem, this is why I asked if we are using the correct gpac_extra_libs.zip.

**Comment by arevi** [comment]
Now doing gpac_build_android I got many errors like:/home/user1/Code/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: cannot find -ljs_osmo
/home/user1/Code/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: cannot find -leditline
/home/user1/Code/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lft2
/home/user1/Code/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: cannot find -ljpegdroid
/home/user1/Code/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lopenjpeg

It looks like they are connected with extra libs, aren't they?

**Comment by fcsteagu** [comment]
you need to copy the extra libraries from gpac_extra_libs/build/libs to gpac/extra_lib/lib/android

**Comment by arevi** [comment]
yes, I did it

**Comment by arevi** [comment]
In readme the different path of source is used, by the way:
Copy the just compiled libs into <GPAC_DIR>/extra_lib/lib/android by entering this command : 
cp -r lib/android/* <GPAC_DIR>/extra_lib/lib/android/

here lib/android, not build/libs

**Comment by fcsteagu** [comment]
hmm I think the libs found in lib/android and the ones found in build/android/libs are the same

**Comment by arevi** [comment]
I got the apk in the end at /home/user1/Code/gpac/applications/osmo4_android, but the output shows me an error "zipalign: error while loading shared libraries: libc++.so: cannot open shared object file: No such file or directory". Can it influence the final apk?
What package is required? I installed lib32stdc++6 lib32z1 lib32z1-dev in Ubuntu, but it didn't help.

**Comment by arevi** [comment]
Osmo4 has the same errors, which I mentioned in the first message here.
Are there any other ideas how to fix them?

**Comment by fcsteagu** [comment]
I'm pretty sure that you have to recompile the gpac extra libs with the cyanogenmod libraries for your device. Please let me know if you fix it like that because I'm also interested. In fact I had the same problem and if I use the first archive in the list that you find here http://download.cyanogenmod.org/?type=snapshot I get rid of that error.

**Comment by arevi** [comment]
Is there any difference between r10 and r10e-rc4?
fcsteagu, what is your host OS, where you make building?
Have you even seen the error "zipalign: error while loading shared libraries: libc++.so: cannot open shared object file: No such file or directory"? (I mentioned about it above)

**Comment by fcsteagu** [comment]
I'm compiling on Ubuntu 12.04.5 LTS and Ubuntu 14.04.2 LTS.
There should be some minor diferences between those NDKs, but nothing to worry about I assume!

If I remember correctly I had an error related to libc++.so and I had to add some path to LD_LIBRAY_PATH. I think that zipalign has libc++.so as dependency and when you are trying to load it, libc++ is not found where it is expected (not sure about this!).
Try to install this
sudo apt-get install lib32stdc++6 lib32z1 lib32z1-dev

**Comment by arevi** [comment]
I've just realised, the link to cyanogenmod is needed only for building of stagefright mode. So, it will not help for master (ordinary) version I suppose.

**Comment by arevi** [comment]
Hello, again.
I got another device - Nesus S with Android 4.1.2 and built gpac (Osmo4) again with target 18 and 16.
Both of them during the launch of Osmo4 gave these errors:
Error
[Core] Cannot load module file /data/data/com.gpac.Osmo4/lib//libgm_ffmpeg_in.so, error is Cannot load library: link_image[1891]: 88 could not load needed library 'libavcodec.so' for 'libgm_ffmpeg_in.so' (find_library[1201]: 88 'libavcodec.so' failed to load previously)
Error
[Core] Cannot load library libgm_ffmpeg_in.so
Error
[Terminal] Did not find any input plugin for URL /data/data/com.gpac.Osmo4/gui/extensions/bifs_tests/ (no mime type)

The revision is the same - 727.
What can be done to fix it?

**Comment by nguyen-viet-thanh-trung** [comment]
Could you please try the latest gpac_extra_lib package: http://download.tsi.telecom-paristech.fr/gpac/gpac_extra_libs.zip ? See README_FIRST for more detail.
Your feedback is welcome !

**Comment by arevi** [comment]
During building process I got an error "libstagefright_h264 not found". I'll try to build it without stagefright mode.

**Comment by arevi** [comment]
nguyen-viet-thanh-trung, can you tell, what OS do you use, what GCC version, SDK and NDK? May be there are other important details.

**Comment by nguyen-viet-thanh-trung** [comment]
Hi arevi,
I use Ubuntu 14.04.2 64 bits, gcc version 4.9.2, Android NDK r10d. From your info, your error occurs while compiling zlib.

For compile with support stagefright, you need also add to ffmpeg-2.4.3/android-source/frameworks/native/include/binder/Binder.h these lines:

#ifdef __cplusplus
#include <atomic>
using namespace std;
#else
#include <stdatomic.h>
#endif

Sorry for missing a README file.

**Comment by arevi** [comment]
Forget to say, my Android device recently self-updated from 5.1 to 6.0, but I guess it's not very important.

**Comment by canatella** [comment]
I had the same problem here and linking using   -Wl,--exclude-libs,libavcodec.a fixes the problem, but don't ask me why. I do not understand why keeping some symbols private would suddenly make calling an abi work. Maybe the code in question is not used and that code get stripped by -Wl,--gc-sections but then this means that stagefright is not working here.

**Comment by jq5** [comment]
Sorry for the long comment:

Hi All,

First off, thank you for all your help.

Similar to 'Ghost' I am having trouble creating a working APK file for a Nexus 6, with OS 6.

I will outline the steps I have taken and if there is anything missing or if I have done something in error, please let me know.

1.	Fresh install of Ubuntu 14.04.02 in VMware Fusion on OSX.  I just needed to stall 'git'.  The following steps have been tested in both a 32-bit and a 64-bit environment.

2.	I use 'git clone https://github.com/gpac/gpac.git' to get a fresh install of gpac.

3.	Prior to building gpac, I download the extra libs from the ubuntu repository using the instructions for 14.04 on:
'https://gpac.wp.mines-telecom.fr/2011/04/20/compiling-gpac-on-ubuntu/' 


Question:  should I use the programs provided in the extra_libs package, rather than downloading them from the ubuntu repository?


4.	I also install ffmpeg, x264 and x265 from this site:
https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu

5.	Finally I install OpenHEVC from:
https://github.com/OpenHEVC/openHEVC

unfortunately, openHEVC only builds in the 64-bit environment, so 32-bit APK does not contain support for HEVC.

At this point I build gpac, './configure && make && sudo make install'

6.	I now install the NDK and SDK for Android:

NDK:	version r10e
downloaded from:
http://developer.android.com/ndk/downloads/index.html#download

SDK:	version 23.0.2
installed as part of the android studio install, from:
http://developer.android.com/sdk/index.html#Other

Prior to installing android studio, I had to install java:
https://www.digitalocean.com/community/tutorials/how-to-install-java-on-ubuntu-with-apt-get

Once android studio is installed, select 'configuration' and install the build targets you want, i.e. 16, 18 and 23 were the targets I selected.

So that there is no zipalign error, I had to add '<SDK-location>/build-tools/23.0.2/' to my PATH, as zipalign is within this folder location.

Create soft links to SDK and NDK in /opt/, using:
cd /opt/
sudo ln -s <Android SDK location> android_sdk
sudo ln -s <Android NDK location> android_ndk

Install ant from ubuntu repository.

7.	I now proceed to download the extra libs.

a.	When I download the extra libs from:
http://download.tsi.telecom-paristech.fr/gpac/gpac_extra_libs.zip 

I get the same error as 'Ghost, i.e. 'libstagefright_h264 not found' for both 32-bit and a 64-bit environments.

b.	so I use the extra libs from: 
https://sourceforge.net/p/gpac/code/HEAD/tree/trunk/gpac_extra_libs/gpac_extra_libs.zip

I did read that the extra libs and the main files should be from the same trunk, so I also built the svn main file with the extra libs, to produce 'Osmo4-0.5.1-DEV-r5619M.apk' but this still would not work (64-bit only).

c.	Once the extra libs are downloaded:
cd 'gpac_extra_libs/build/android/'

and execute the 'gpac_build_all_extra_libs' shell script, add the location of the NDK as a parameter to the script.

This creates a folder called 'libs' which contains 3 folders, namely 'armeabi, armeabi-v7a and x86', each containing 16 *.so files:
libavcodec.so   libeditline.so   libjs_osmo.so   libstlport_shared.so
libavfilter.so  libfaad.so       libmad.so       libswresample.so
libavformat.so  libft2.so        libopenjpeg.so  libswscale.so
libavutil.so    libjpegdroid.so  libpng.so       libz.so

Copy these 3 folders to 'gpac/extra_lib/lib/android'

8.	get real3d.jar

Download from:
http://developer.lge.com/sdk/android/Real3D_SDK_api-14_r01.zip

unzip and real3d.jar is located in 'libs'

copy real3d.jar into folder gpac/applications/osmo4_android/libs.

9.	Then cd to 'gpac/build/android/jni' and execute:

./gpac_build_android -ndk=/opt/android_ndk -sdk=/opt/android_sdk -ant=ant -force_rebuild

This creates two APK files:
osmo4-0.5.2-DEV-rev1101-g153d4d3-master.apk
osmo4-0.5.2-DEV-rev1101-g153d4d3-master-stagefright.apk

When I test the non stagefright APK I get:
"Error
[Codec] ODM1 ES1: Cannot find decoder for stream type MPEG-4 AVC|H264 Video", and then the screen tried to decode but I get fragmented lines.

When I tested with x86 included in the non stagefright APK, I get the same as 'Ghost' (see note b below):
"Error
[Core] Cannot load module file /data/data/com.gpac.Osmo4/lib//libgm_ffmpeg_in.so, error is dlopen failed: cannot locate symbol "_ZN7android16MediaBufferGroup14acquire_bufferEPPNS_11MediaBufferE" referenced by "libavcodec.so"...
"Error
[Core] Cannot load library libgm_ffmepg_in.so"

Then when I try and load a test clip, I get:
"Error
[Codec] ODM1 ES1: Cannot find decoder for stream type MPEG-4 AVC|H264 Video", and then the screen tried to decode but I get fragmented lines.

Note:
From your binary, I note that:
a.	both x264 and x265 work, so do you use a 64-bit development environment? 

b.	When I extract the contents of the APK file 'osmo4-0.5.2-DEV-latest-master.apk', I can see that within 'lib', each of the 3 folders, 'armeabi armeabi-v7a x86', contain 45 items. 

When I look within my generated APK file 'osmo4-0.5.2-DEV-rev1101-g153d4d3-master.apk', I can see that within 'lib', only 2 folders contain 45 items, 'armeabi armeabi-v7a', while 'x86' only contain 16 items. 
When I look at 'Application.mk' from gpac/build/android/jni/ I can see 'APP_ABI := armeabi armeabi-v7a' which means that x86 is not built, so why does your APK contain all the correct files? I noted that the file change on github states that x86 was no longer supported.  Am I doing something wrong?

When I re-enable the x86 in Application.mk, it then gives the additional errors outlined above.

c.	I also note that my APK files are approximately 27MB including x86, and 24.5MB excluding x86, while your master APK is only 22.6MB.

I notice that 'libavcodec.so' is approx 2.6MB larger than yours in the extracted lib folders of 'armeabi armeabi-v7a x86'.  While there is a small increase in some of the other .so files.


Questions:
A.	Which O/S and which 32/64-bit should I use.
b.	Which of the locations, git or svn, is used to build the binaries?
c.	Can you provide the options that the 'buildbot' uses to create the APK files.
d.     I'm confused as to why my APK is larger than yours but contains less files than yours (the APK without x86).


Again thank you for all your help.

**Comment by nguyen-viet-thanh-trung** [comment]
Hi jq5,

You should use the extra_libs from http://download.tsi.telecom-paristech.fr/gpac/gpac_extra_libs.zip, the one from svn is too old.
While compiling extra libs:
- if you don't need stagefright: comment this line in build/android/gpac_build_all_extra_libs: ./compile_ffmpeg_libstagefright_android.sh $1 || exit 1. 
- if you want to test stagefright version. add to ffmpeg-2.4.3/android-source/frameworks/native/include/binder/Binder.h these lines:
#ifdef __cplusplus
#include 
using namespace std;
#else
#include 
#endif

**Comment by jq5** [comment]
Hi Nguyen,

Thank you for letting me know that the svn libs are outdated.

I have now compiled and built a working APK, for both x264 and x265, for the nexus 6.  Of course stagefright does not work.

As outlined by 'Ghost', when I include 'stage fright' in the build, I get a build error "libstagefright_h264 not found".

In addition to the change outlined for 'compile_ffmpeg_libstagefright_android.sh'.  I had to comment out a few extra items to make the APK build without stagefright.

The following are the steps I used to build:
1.  First off, make sure to unzip all the zipped files: 'unzip all.sh'.  This removes the 'adler32.c' errors seen by 'Ghost'.

2.   in build/android/jni/Android.mk, I had to comment out:
# include $(LOCAL_PATH)/lib_ffmpeg_stagefright.mk

3.  in build/android/jni/Application.mk, I had to remove all stagefright files:
APP_MODULES := libz libfaad libft2 libjpegdroid editline libjs_osmo libopenjpeg libpng libmad libavcodec libavformat libswscale libavutil libavfilter libwsresample stlport_shared libavcodec_stagefright libavformat_stagefright libswscale_stagefright libavutil_stagefright libavfilter_stagefright libwsresample_stagefright

to

APP_MODULES := libz libfaad libft2 libjpegdroid editline libjs_osmo libopenjpeg libpng libmad libavcodec libavformat libswscale libavutil libavfilter libwsresample stlport_shared

4.  This builds the libs folders, move these to 'gpac/extra_lib/lib/android' and run './gpac_build_android -ndk=/opt/android_ndk -sdk=/opt/android_sdk -ant=ant -force_rebuild'.  I had to comment out all the build code for 'stagefright' in gpac_build_android, lines 204 to 230.

I had a quick look at the difference between this extra lib and the svn version:

I noted that in the svn, build_libstagefright, we have line:
FLAGS="$FLAGS --cross-prefix=$TOOLCHAIN/bin/arm-linux-androideabi- --cpu=armv7-a --enable-libstagefright-h264"
while in the new zip, we have:
FLAGS="$FLAGS --cross-prefix=$TOOLCHAIN/bin/arm-linux-androideabi- --cpu=armv7-a --enable-libstagefright-h264 --enable-decoder=libstagefright_h26"

Even when I swop these out, I still get the same build error:
  inflating: ../system/lib/soundfx/libvisualizer.so  
  inflating: ../system/lib/ssl/engines/libkeystore.so  
Configuring ...
ERROR: libstagefright_h264 not found

Again, thank you for all your help.

**Comment by jeanlf** [comment]
we removed stagefright from our builds, check latest version (MediaCodec)

**Comment by mdasari823** [comment]
**unzip_all.sh** should solve the issues faced by @ghost about finding **adler.c**.

**Comment by azhar5678** [comment]
hey jeanlf i have osmo apk that do not run on android 4.2 
error unable to load .so file

please upload a full working apk on gpac website
