### ISSUE TITLE
What is Chroma format ?

### ISSUE THREAD

**Issue by combucha** [gpac/gpac#357]
Since (around) GPAC 0.5.1 mp4box sets this value which is reported in -info, usually:
Chroma format 1 - Luma bit depth 8 - chroma bit depth 8
Older builds didn't do that.
If I remux that old mp4's with newer mp4box, -info flush this:
Chroma format 0 - Luma bit depth 8 - chroma bit depth 8
I recently joined some files and the first part hadn't set chroma value, so final file has chroma format from 1st chunk - 0. I can remux whole movie, that will change chroma format to 1, but should I bother with this... what this value actually causes?

...and I've noticed that after removing audio track, IOD root has no Audio PL updated (old value stored)

**Comment by rbouqueau** [comment]
You may know that pictures are described by planes like RGB. There exists another representation called YUV. Y is the luma, and U&V are called the chroma. We display the chroma format (codecs may support several flavours).

Let me know if this has an impact on your file (it shouldn't). Otherwise consider cloing this issue, thanks.
