### ISSUE TITLE
Representation segment index doesn't start with a segment index box which indexes the index segment

### ISSUE THREAD

**Issue by brendanlong** [gpac/gpac#36]
Sorry about the long title.

In 6.4.6.3 Representation Index Segment:

> The Segment Index for each Media Segments is concatenated in order, preceded by a single
> Segment Index box that indexes the Index Segment. This initial Segment Index box shall have one
> entry in its loop for each Media Segment, and each entry refers to the Segment Index information for
> a single Media Segment.

When I use MP4Box to create a DASH stream from MPEG-TS files, the representation index doesn't start with this initial segment index box, but instead just has the segment indexes for media segments.

**Comment by brendanlong** [comment]
Essentially, a valid segment index file starts with:

styp ; sidx (all reference_types = 1) ; sidx (all reference_types = 0) ; sidx (all reference_types = 0) ; etc.

**Comment by brendanlong** [comment]
Most likely this requires changes in `src/media_tools/dash_segmenter.c`. See `m2ts_sidx_flush_entry` and `dasher_mp2t_segment_file` in particular. It's not clear to me how to hold off on writing the indexes until we have all of them so we can write the master index first.

**Comment by brendanlong** [comment]
Looking at a representation index I have, it looks like it only has one 'sidx'. The spec says:

> The Segment Index for each Media Segments is concatenated in order, preceded by a single
Segment Index box that indexes the Index Segment. This initial Segment Index box shall have one
entry in its loop for each Media Segment, and each entry refers to the Segment Index information for
a single Media Segment.

This is confusingly written, but since the master 'sidx' has one entry per segment, and each entry points to "the" index for a segment, that seems to imply that each media segment has exactly one 'sidx', and segments can't share an 'sidx'.

I'll bring this up at the next MPEG meeting and make sure that this is the intent, and if so, as if it can be made more explicit.

**Comment by jeanlf** [comment]
There are actually two possibilities:
- either using a representation index which is a master sidx with sub sidx for each segment; in this case, only one index is used for the whole representation
- or using a separate index which is a regular sidx, potentially chained

In any case we do it wrong :) I have for the time being commented the generation of the sidx file, since it is optional, so that we don't generate non-conformant sequences. 
As you noticed, patching the code will require a bit of time since this code was not originally designed to produce indexes as decided in the DASH standard.

**Comment by jeanlf** [comment]
proper segment indexing for TS should now be supported in 0.9.0 dev branch
