### ISSUE TITLE
default modules not found (MP4Client) 

### ISSUE THREAD

**Issue by sergiomb2** [gpac/gpac#370]
from https://sourceforge.net/p/gpac/discussion/287547/thread/904ae7e1/ 

GPAC looks for modules in the following directories: /usr/lib/gpac, /usr/local/lib/gpac, /opt/lib/gpac, /opt/local/lib/gpac. Do you have any of them on your disk? Otherwise you should find where the module directory is with 'locate' and add it to your LD_LIBRARY_PATH.

suggest do: sudo ln -s /usr/lib/i386-linux-gnu/gpac /opt/lib/gpac 
but maybe it is better add /usr/lib64/gpac/ to the search PATH

Thanks

**Comment by kwizart** [comment]
Gpac should follow the path that was configured at ./configure step.
In the Fedora case, the libdir is /usr/lib or /usr/lib64 based on what is given at the ./configure step by the RPM %configure macro. So the search path for the gpac module is %{_libdir}/gpac

**Comment by rbouqueau** [comment]
First thank you for reporting.

> suggest do: sudo ln -s /usr/lib/i386-linux-gnu/gpac /opt/lib/gpac 

This should already be fixed almost a year ago: https://github.com/gpac/gpac/commit/e2ce23d3b621bd8a13441b49c71b905421d2b0bd

There may be a bug. Which version of GPAC do you use? (probably your distribution using an older version but I want to make sure)

> but maybe it is better add /usr/lib64/gpac/ to the search PATH

I've just added it, thanks.

> Gpac should follow the path that was configured at ./configure step.

Good idea, thanks for the suggestion. Let me have a look

**Comment by sergiomb2** [comment]
> Which version of GPAC do you use? (probably your distribution using an older version but I want to make sure)

gpac-0.5.2, usually we just use released versions.

**Comment by rbouqueau** [comment]
Could you tell me what ```MP4Box -version``` says?

**Comment by sergiomb2** [comment]
MP4Box -version
MP4Box - GPAC version 0.5.1-DEV-rev4065
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --enable-debug --extra-cflags=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -fPIC -DPIC -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D_LARGEFILE_SOURCE=1 -D_GNU_SOURCE=1 -I/usr/include/ffmpeg  --X11-path=/usr --libdir=lib64 --disable-oss-audio --disable-static --use-js=no
Features: GPAC_64_BITS GPAC_HAS_SSL GPAC_HAS_JPEG GPAC_HAS_PNG

**Comment by rbouqueau** [comment]
That version is from 2012: https://sourceforge.net/p/gpac/code/4065/. Would it be possible for you to update somehow? Are you able to rebuild for example?

**Comment by sergiomb2** [comment]
The version that we are using is https://github.com/gpac/gpac/archive/v0.5.2.tar.gz (tagged this on 20 Jan 2015)  configure marked as revision 4065 , because no .svn file was found : 
 
    if [ -d ".svn" ]; then
    (...)
    else
     if [ ! -e "$source_path/include/gpac/revision.h" ]; then
        echo "#define GPAC_SVN_REVISION \"4065\"" > $source_path/include/gpac/revision.h
     fi
    fi

what version, git commit do you suggest to update ? we, like any other distribution, are waiting for a new release , stable release preferably.

**Comment by rbouqueau** [comment]
We are not good at doing releases. We've plan to do one soon for the last 6 months.

Currently we rely on our buildbots (which include many builds + tests) to guarantee the stability of the software. So any release should be ok. That's what Ubuntu and Debian do - I don't know for the other distributions and I am happy that you are here. Any advice is warmly welcome to ease your job.

The svn is not maintained any more. The equivalent revision for th 0.5.2 is svn5617 (you can see it from this page: https://github.com/gpac/gpac/commit/cb0a053f47173556f193c2d996262d8c6aaac9bb). Since then we have deprecated the svn in favour of our github account (https://gpac.wp.mines-telecom.fr/2014/11/21/gpac-is-now-on-github/).

We have set commits number starting at the latest tag (0.5.2). It is commited using this code:
- https://github.com/gpac/gpac/blob/3ab2a2038273259eb5d9aeea1f9a3bb72a44d4b9/Makefile#L16
and you can find these numbers on our nightly builds:
- https://gpac.wp.mines-telecom.fr/downloads/gpac-nightly-builds/

Please let us know if you have any questions or feedback. We appreciate your work and would be happy to make it easier if we can.

**Comment by kwizart** [comment]
@rbouqueau 
You patch "add /usr/lib64 for a possible module path for Fedora" isn't optimal. At the very least the order need to be reversed between the /usr/lib/gpac and /usr/lib64/gpac. But we are going to enter very gory details by not having followed the correct fix that would probably works with any distribution, such as module path coded at configure time. And to have an environment variable to eventually override that at runtime. (This is was is usually done in such case, have a look on libvdpau for a sample).

The reason for lib64 over lib is that fedora, as many other distributions is multi-libs (at least on x86_64). This means two ABI are provided for x86 , as 64bit and 32bit (the latter only as needed).
The primary path for libraries is then /usr/lib64 on such system, so that "legacy 32bit x86" can still be installed in /usr/lib as previously.
Now most binary are provided once as the native architecture ISA. So gpac binaries are on 64bit, but it is possible to install gpac-libs as 32bit (in /usr/lib/gpac). This is useful so binaries provided by others, as 32bit an using system libraries, can still be installed.
In this case the gpac x86_64 binaries will try to open the 32bit libraries first.

**Comment by sergiomb2** [comment]
Hello 
I have just learned that  git describe count the commits after last tag , so gpac nightly builds versions , are done with a command similar to: 

    git describe | sed "s/^v0.5.2-//" 

So every commit is a new version ... 
Looking at Debian state and Ubuntu [1] , they stopped at 426 commit , you go at 1200, like I said, Distributions wait for stable releases, so or you do a new tag or we choose a commit to package, time to time, but if we don't follow the development, like me, we have much more risks for breaking things. Conclusion it was better you make some tags.

[1] https://tracker.debian.org/pkg/gpac

**Comment by rbouqueau** [comment]
> At the very least the order need to be reversed between the /usr/lib/gpac and /usr/lib64/gpac

Ok thanks for the explanation. It didn't know about that. Commit done.

> the correct fix that would probably works with any distribution, such as module path coded at configure time

I plan to add that.

> And to have an environment variable to eventually override that at runtime. (This is was is usually done in such case, have a look on libvdpau for a sample).

Good idea too, thanks for sharing, we'll discuss that internally.

> Looking at Debian state and Ubuntu [1] , they stopped at 426 commit

Debian updated about 6 months ago. They usually update once to twice a year which sounds ok given our development pace.

> Distributions wait for stable releases, so or you do a new tag or we choose a commit to package, time to time, but if we don't follow the development, like me, we have much more risks for breaking things. Conclusion it was better you make some tags.

That's one of our priority. Our users ask us for more clarification too.

**Comment by goeranu** [comment]
Wouldn't it make sense to let the `configure` script write a definition of `GPAC_MODDIR` to `config.h`, using the same value as for `moddir` in `config.mak`.  And then use this directory name for the lookup in `os_config_init.c`

    if (check_file_exists(TEST_MODULE, GPAC_MODDIR, file_path)) return 1;

Wouldn't that be able to replace *all* the other attempts, and get rid of the guessing?

Apologies if this is naïve, but something along those lines is what I would have expected given how other projects typically do.

**Comment by sergiomb2** [comment]
@rbouqueau  , please do a tag and call it whatever you want for exemple: hiperalfa , but if you do a tag, we (distros) could package the same thing and test the same thing and start work on that , is just  group some commits, no more than that. 

Thanks.

**Comment by rbouqueau** [comment]
We're going to tag by the end of the week.

**Comment by rbouqueau** [comment]
Release done: https://github.com/gpac/gpac/releases/tag/v0.6.0. Thanks for your patience.

**Comment by jeanlf** [comment]
I think this can be closed, at least for single-arch. If you mix x86_64 and i386 modules, you will need to enable additional module directories by hand in the config file
