### ISSUE TITLE
[Android] Some streams are played at 24000

### ISSUE THREAD

**Issue by canatella** [gpac/gpac#45]
When playing some streams on Android, the audio is not played at the right sampling rate. In function 
```c
static GF_Err WAV_QueryOutputSampleRate(GF_AudioOutput *dr, u32 *desired_samplerate, u32 *NbChannels, u32 *nbBitsPerSample)
```
in modules/droid_audio/droid_audio.c, the desired_samplerate is argument is 24000 where the actual stream's sample rate is 48000.

**Comment by jeanlf** [comment]
please provide a test sequence, we'll have a look

**Comment by canatella** [comment]
Romain as the link to the problematic stream. I cannot publish it here, but just playing the stream here is enough to reproduce the problem.

**Comment by canatella** [comment]
In fact the playback is quite problematic, even when forcing the audio. It never display a picture here in Osmo4_android and audio is quite choppy.

**Comment by rbouqueau** [comment]
Since some of the issues may be done by stagefright. Could you please try to build FFmpeg without it?
PS: our builds http://gpac.io/downloads/gpac-nightly-builds/#Android

**Comment by canatella** [comment]
Just tested, It's the same problem with both stagefright and non-stagefright builds.

**Comment by rbouqueau** [comment]
Apparently the ConfigureOutput() SampleRate argument is 24000 on Android, 48000 on the Desktop version (I just checked with the dx_out module and everything is fine). On Android the playback is garbage unless the 48000 value is forced.

@jeanlf @nguyen-viet-thanh-trung Do you know any way to easily check if the issue comes from the decoder (e.g. FFmpeg reporting 24000 instead of 48000) or elsewhere? Logs?

**Comment by rbouqueau** [comment]
may be related to #62

**Comment by nguyen-viet-thanh-trung** [comment]
This bug should be fixed now. Could you please check rev118 solve this isssue and also #46 ?
