### ISSUE TITLE
Unable to play dash content - Help needed

### ISSUE THREAD

**Issue by merargin** [gpac/gpac#456]
Hi,

I created dash content, but it is not played using media source extensions.

Video link: https://www.dropbox.com/s/jcwl589nmkv5cz4/v1out_dashinit.mp4?dl=0

MPD file link: https://www.dropbox.com/s/bo1cc3ejyh9kzr0/v1out_dash.mpd?dl=0

Someone please advise me to play the video using JavaScript MSE.

Regards,
Xavier

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by rbouqueau** [comment]
First: please fill your issue correctly. You still have the checkboxes at the end of your own message.

Then: is your content comformant? www.dashif.org/conformance.html

**Comment by merargin** [comment]
Conformance test completed. 

✓XLink resolving
✓ MPD validation
✓ Schematron validation

**Comment by rbouqueau** [comment]
Please provided the required additional information: platform, command-line, etc.

**Comment by merargin** [comment]
I am using CentOs.  Used the following commands to create dash contents.

ffmpeg -i v1.mp4 -s 1280x720 -c:v libx264 -b:v 1450k -bf 2 -g 90 -sc_threshold 0 -c:a aac -strict experimental -b:a 96k -ar 32000 v1out.mp4

MP4Box -dash 10000 -rap v1out.mp4

**Comment by rbouqueau** [comment]
I don't think that's respectful not to follow our guidelines. And you should really read what was done by other people who succeeded.

Which player, which browser, which version of the OS etc. please?

My guess at this point is that this issue is unrelated to GPAC. You could:
1) encode properly: http://blog.streamroot.io/encode-multi-bitrate-videos-mpeg-dash-mse-based-media-players/
1 bis) check your media content: http://gpac.io/2015/11/02/check-key-frame-alignment-with-mp4box/
2) use the right DASH profiles (depending on your use case): http://www.gpac-licensing.com/2014/08/21/ibc-2014-dash-avc264-support-in-gpac/

Also you could check at what other people on our forums and others did.

If you think the information is too hard to gather, a suggestion (like a pull request on the wiki) would be highly appreciated.

**Comment by merargin** [comment]
OS: CentOS release 6.4 (Final)
Browser: Chrome: 48.0
Player: Not using any external player. Written simple js [player](https://www.dropbox.com/s/kuzydoziqjszin3/dashplayer.js?dl=0).

We are unable to encode the video as per the info from http://blog.streamroot.io/encode-multi-bitrate-videos-mpeg-dash-mse-based-media-players/. It shows "Unknown encoder 'libfdk_aac' ". Trying to fix this problem. I will do all the steps mentioned by you and will get back to you soon.

Thank you very much for your information and help.

**Comment by merargin** [comment]
Hi Romain Bouqueau,

Fixed all issues and mpeg-dash is working fine now. Thanks for your help.

Regards,
Xavier
