### ISSUE TITLE
Audio Segments will have weird rumbling noise if the input sampling rate is not 44100 Hz

### ISSUE THREAD

**Issue by carterh062** [gpac/gpac#461]
There is a post here: https://sourceforge.net/p/gpac/bugs/349/ that is about this, but no open Github issues. It took me a while to get to the bottom of it, so I wanted to open an issue on Github. Not sure if this is the right protocol, but I thought it may help someone.

My fix is to take my input stream ( which happens to be coming from rtmp ) and use ffmpeg to re-encode the audio with aac to stereo with 44100 Hz and send it to a udp output that DashCast can read from. 

The command looks like the following:
`ffmpeg -i [input] -c:a aac -ar 44100 -ac 2 -c:v copy udp://127.0.0.1:1234?pkt_size=13`

**Comment by lmoesch** [comment]
This is an issue appearing now for years and no solution so far. As far as I remember from trying to solve the issue, the problem is the synchronisation between video and audio segments.

So you do not just have a "rumbling" in your audio, it's a complete de-sychronisation of your audiotrack, wich leads to an audio drift.

**Comment by jeanlf** [comment]
dashcast is now deprecated, use GPAC 0.9.0
