### ISSUE TITLE
Seeking is very slow in specific MP4

### ISSUE THREAD

**Issue by amuth** [gpac/gpac#463]
Hello,

I have generated an mp4-Video (HEVC - x265) with mp4box.exe (v0.6.2 rev.49). Fast forward or rewind - the VLC Player is very slow / hangs. 

I had reported this error ever in sourceforce "https://sourceforge.net/p/gpac/bugs/353/".
Then I set the error on VLC "https://trac.videolan.org/vlc/ticket/16732#no4".

Result from VLC: Video track does provide stss which only tells first frame as sync point. 
--> Broken file.

Please fix it...

**Comment by cconcolato** [comment]
The issue on SourceForge was closed because there was an answer. That same answer is still applicable here. Let me explain.

Your video stream has only one IDR frame at the beginning and then 26 CRA in the middle. 
There is a corrigendum (under discussion at MPEG) to fix the signaling of CRA in MP4 files. MP4Box implements this corrigendum, which says:
- Only IDR shall be marked as sync samples 
- CRA/BLA are not marked as sync samples
- The sample group "rap" is used to mark CRA and BLA as random access point. 

If your player does not support that signaling, you can always use "forcesync" as indicated on SourceForge.

We might revisit this behavior if MPEG's corrigendum changes or is not adopted.

**Comment by amuth** [comment]
Thank you very much.
