### ISSUE TITLE
MP4Box supported iTunes tags

### ISSUE THREAD

**Issue by 4getit** [gpac/gpac#465]
Hello,

Currently for iTunes, the -itags list seems really limited:

_MP4Box -tag-list
Supported iTunes tag modifiers:
    album_artist    usage: album_artist=album artist
    album   usage: album=name
    tracknum    usage: track=x/N
    track   usage: track=name
    artist  usage: artist=name
    comment usage: comment=any comment
    compilation usage: compilation=yes,no
    composer    usage: composer=name
    created usage: created=time
    disk    usage: disk=x/N
    tool    usage: tool=name
    genre   usage: genre=name
    name    usage: name=name
    tempo   usage: tempo=integer
    writer  usage: writer=name
    group   usage: group=name
    cover   usage: cover=file.jpg,file.png
    encoder usage: encoder=name
    gapless usage: gapless=yes,no
    all usage: all=NULL_

Am I missing something or was this done on purpose (because there is another way)? 
There are quite some significant ones missing.

For example, how do I set things like:
- Video Type (Movie, TV Show, Home Video etc.)
- Season
- Episode
- Episode Title
- Episode ID
- HD Video
- Short Description/synopsis
- Long Description/plot
- iTunEXTC for rating 
- iTunMOVI for the rest (Cast, Director, Producer etc.)

There more missing like xid, Artist ID, Lyrics, Playlist ID etc.

I had hoped I could do something with setting things like: MP4Box -set-meta "desc=Some Description" output.m4v 
... but I guess that's for something else because it doesn't seem to do anything. Also, that way I wouldn't know how to add iTunEXTC and iTunMOVI.

Is there a workaround to somehow get these -itags in? Maybe using -udta somehow?
If not, would it be a good addition to add more options to the supported list?

**Comment by jeanlf** [comment]
a lot of these were added quite some time ago and the list never got updated. There is unfortunately no simple way to design a generic mechanism, each tag using a different syntax ...
If you have a link to the spec for each tag description (syntax and 4cc) implementing these could be quite simple.

**Comment by Jamaika1** [comment]
How to support 'Enter' {hex: 0d0a} in the comments? In the DOS, I can not add. Can the contents of the iTunes entered in xml?

> I had hoped I could do something with setting things like: MP4Box -set-meta "desc=Some Description" output.m4v

The 'set-meta' always creates a new item. Even if you ask 'mdir' assigned to the metadata it will not be assigned to the metadata. The same problem applies to add attachments. They are invisible.

**Comment by jeanlf** [comment]
Now available on git for `-itags`option:
- more tags support
- possibility to load tags from file (typically for multi-line payload such as lyrics, comments, ...)
- possibility to define custom string tags using their 4CC values

See `MP4Box -h tags`

**Comment by Crissov** [comment]
@jeanlf I’m not sure whether `hdvd` should (still) be treated as a boolean. I believe it is an integer, but am not sure. 

There is a number of [optional 4CC that used to be documented by Apple](https://github.com/mp4ra/mp4ra.github.io/issues/115):

> The following tags may also be used; not all software recognizes or interprets them

_Art Director_ `©ard`,
_Arranger_	`©arg`,	
_Lyricist/Author_	`©aut`,
_Copyright Acknowledgement(s)_ `©cak`,
_Conductor_ `©con` (this one is used indeed),
_Song Description_	`©des`,
_Director_	`©dir` (in actual use),
_Equalization preset name_	`©equ`,
_Liner Notes_	`©lnt`,
_Record Company_ `©mak`,
_Original Artist_ `©ope`,
_Phonogram Rights_ (P-Line) `©phg`,
_Producer_ `©prd`,
_Performer_ `©prf`,
_Publisher_ `©pub`,
_Sound Engineer_ `©sne`,
_Soloist_ `©sol`,
_Credits_ `©src`,
_Thanks/Dedications_ `©thx`,
_Online Extras_ `©url`,
_Executive Producer_ `©xpd`.

I’m not sure, whether they were ever supported by any software since their metadata fields are now usually mapped to `----:com.apple.iTunes:FOOBAR`.
