### ISSUE TITLE
Request: MP4Client to output to stdout

### ISSUE THREAD

**Issue by Mac0z** [gpac/gpac#52]
This is a feature request rather than a bug, but it would be very useful if MP4Client could output the data to stdout rather than direct to the audio/visual hardware.

While I'm sure many developers/users would find this useful for chaining the output to other commands, my specific use would be to allow playback of MPEG-DASH streams within the squeezebox music system. There is a plugin which will play simple DASH streams created by MP4Box using vlc to handle the transcoding (see https://github.com/Mac0z/playDASH) but this cannot handle more complex streams such as the BBC's test MPEG-DASH feed (http://rdmedia.bbc.co.uk/dash/ondemand/bbb/2/client_manifest-audio.mpd) which MP4Client handles perfectly.

**Comment by jeanlf** [comment]
We're thinking about that but it's a bit more complex than a straight stdout redirection:
- audio and video may need to be sent on different pipes
- reconfiguration may happen (audio sample rate change, video resolution change), which will need to be signalled in some way

Handling this in compressed domain is not always possible, since the way DASH switching works may not always allow for direct concatenation of files (multiple moov boxes -> invalid content). This would require a complete remuxing of the source which we don't support yet.

we'll keep you posted whenever we progress on that topic...

**Comment by Mac0z** [comment]
Thanks for the update, I appreciate it's not simple

**Comment by jeanlf** [comment]
Now possible in 0.9.0 dev branch, see https://github.com/gpac/gpac/wiki/olay-composition
