### ISSUE TITLE
API/ABI changes review for GPAC

### ISSUE THREAD

**Issue by lvc** [gpac/gpac#799]
May be useful for tracking API/ABI symbols in the library: https://abi-laboratory.pro/tracker/timeline/gpac/

The report is created with the help of open-source abi-tracker tool: https://github.com/lvc/abi-tracker

Thank you.

![gpac-1](https://cloud.githubusercontent.com/assets/1517837/25042005/aea12d1c-2125-11e7-8691-5ec1769d846d.png)
![gpac-2](https://cloud.githubusercontent.com/assets/1517837/25042007/b2f10c02-2125-11e7-98b2-adaa6cf5c25a.png)

## Environment
* Linux x86_64
* GCC 4.9
* GPAC 0.5.0 and higher

**Comment by jeanlf** [comment]
thanks, linking to #217

**Comment by rbouqueau** [comment]
That's great thanks. Now I see that since the latest tag we have only a 55.9% of compatibility (report: https://tests.gpac.io/testres/abicheck/6).

@jeanlf @aureliendavid Is it a metric we plan to stabilize? Do we have some politics about version (ABI/API or public) dumps w.r.t to API/ABI breakage?

**Comment by aureliendavid** [comment]
This is a first try to integrate the tool into our tests pipeline, and to open discussions on what we want to do with it. 

To me the central question is what reference do we compare to, and how to validate a new reference. 

Right now I've based references on commits only and used the last tag v1.0.1 as the reference to test the integration because I knew there would be a bunch of differences. 

To use a new reference for now we need to download the dump file from the interface and push it to a specific git repo. 

This is all up to refinements and discussion. 

For example I thought using the previous commit as a reference wouldn't be a great idea because the next one after that would kind of erase the changes. 

I think the best reference would probably be : the last commit with the exact same major/minor/revision numbers in the lib. 

The next question becomes : does this needs to be automated or can we just say that when the lib version is changed the author manually validates this as the new abi reference. 

 
Lots to be defined.

**Comment by rbouqueau** [comment]
> To me the central question is what reference do we compare to, and how to validate a new reference.

I think there are only 2 references if we only develop on master (and supposedly branch at each major release for bug fixing):
 - last commit: if we break ABI/API, should increase the internal/.so versioning immediately? I think so since we encourage people to use the latest dev version
 - last tag from the same branch (or same version): I would say that within a released version, we should not break the ABI/API (if we did so, we would also take the risk of ABI version collision (with an increase on a version branch while another increase could have happened on master => requires an updated policy on ABI versions https://github.com/gpac/gpac/blob/dcd7c11e500e9740641fde01b27fd695eeaa2698/include/gpac/version.h#L47 (e.g. using odd numbers as dev versions, bumping when branching and then only changing minor/micro on branches, etc.).

Doing this automatically (using a precommit.sh script or adding subsequent commit from a git hook) would eventually help a lot.

My only fear is that we get so many updates that we rapidly have a libgpac.so.1789 ;)

**Comment by aureliendavid** [comment]
The part I was talking about maybe automating was just taking a new reference for the abi compliance tool to check, not actually bumping the lib version automatically, that seem a bit too dangerous to me. 

As to changes wrt last tag : my understanding is that once v1.0.1 is released, we are currently developing v1.1.0-DEV so maybe it is acceptable to have breaking changes between these two?

I agree that we need to clarify the policy about all this.

**Comment by jeanlf** [comment]
> As to changes wrt last tag : my understanding is that once v1.0.1 is released, we are currently developing v1.1.0-DEV so maybe it is acceptable to have breaking changes between these two?

I would say so yes. My idea was
-  to match major (currently 10 in v1.0) to the version number (so bump to 11 when we release v1.1)
-  to bump minor whenever we break API/ABI backward compatibility, not when we add new functions
-  to bump micro when new functions are introduced

would that make sense to you ?

**Comment by rbouqueau** [comment]
> bumping the lib version automatically, that seem a bit too dangerous to me.

For me too. Alternately I could propose to try release way more often. What to you think?

> As to changes wrt last tag : my understanding is that once v1.0.1 is released, we are currently developing v1.1.0-DEV so maybe it is acceptable to have breaking changes between these two?

That would certainly work better if we didn't develop on the master branch ;o

> I would say so yes. My idea was
> *  to match major (currently 10 in v1.0) to the version number (so bump to 11 when we release v1.
> * to bump minor whenever we break API/ABI backward compatibility, not when we add new functions
> * to bump micro when new functions are introduced
> 
> would that make sense to you ?

For what it brings on the table, I found our discussions back in 2014 on this subject:
 * Major: API is broken
 * Minor: API changed but backward-compatible
 * Micro:  what we want (e.g. commit number since last major/micro change)

I personally have no strong opinion, aside from making ABI/API breakage tracable:
1) For devs who should limit them.
2) For users who should not deal with this issue.

To answer to @jeanlf 's proposal I don't think matching the major with the version number is a good idea. Most users link against libgpac.so.10 ; we should change this number wisely (but we have quite full control on minor/micro).
