### ISSUE TITLE
[HLS] Attributes are reseted at each new sub playlist.

### ISSUE THREAD

**Issue by canatella** [gpac/gpac#80]
Commit 1e09acb2340e1ad82118187e133732b3e6a4c5d2 added a call to reset_attributes() in gf_m3u8_parse_sub_playlist() when encountering a new subplaylist. This should not be the case as attributes are cumulative, they should be reused for each subplaylist I think.

@jeanlf, any idea why that call was added ?

**Comment by jeanlf** [comment]
Hmm can't find where the spec states these attributes are cumulative, could you point me to the right section ? My understanding is that these attributes apply to the whole sub-playlist but are not cumulated across playlists / in the master playlist.

The patch was made because we encounter playlists with audio-only TS sub-playlist together with AV TS subplaylists, where the audio-only has only a codecs attribute while the AV have no codecs and resolution attributes. Not resetting the context was making the audio-only have a resolution, hence detectable as AV content.
I can half-revert by only resetting the resolution attribute if needed.

**Comment by canatella** [comment]
The server MUST encrypt every media file in a Playlist using the
    method and other attributes specified by the EXT-X-KEY tag that most
    immediately precedes its URI in the Playlist file.  Media files
    preceded by an EXT-X-KEY tag whose METHOD is NONE, or not preceded by
    any EXT-X-KEY tag, MUST NOT be encrypted.

They say "most immediately precedes". But indeed this is only for the key tag. Note that the reset_attribute() also reset the media_sequence which cause it to be wrong but it has no impact but for decryption I think.
