### ISSUE TITLE
Installing gpac deleted all PATH variables

### ISSUE THREAD

**Issue by rhazor** [gpac/gpac#825]
Very very nice. All PATH variables are replaced with just three gpac entries.

![systempropertiesadvanced_2017-05-05_16-51-17](https://cloud.githubusercontent.com/assets/22996586/25748247/23924780-31b3-11e7-89df-aec0f2f2b677.png)

Just great, I'm not mad at all.

**Comment by aureliendavid** [comment]
Argh, that's not good indeed. 

If you haven't rebooted yet you can probably restore it by doing one of the things suggested here: https://superuser.com/questions/523688/deleted-path-environment-variable-how-to-restore

**Comment by rhazor** [comment]
Okay. But maybe this should be fixed.

**Comment by aureliendavid** [comment]
Absolutely. I was just trying to suggest something to undo the damage while we fix it.

**Comment by aureliendavid** [comment]
@rhazor can you provide some more info on your install because I can't seem to replicate it

what version of gpac, installer binary file, OS etc. are you using? 

I can see that it writes itself 3 times in the PATH for some reason, but I don't see it erase the already present entries. 

Did it affect both the system PATH and the user PATH? 

it should only write to the user PATH and most other PATH entries should be in the system one (the user PATH can be empty, so maybe it didn't delete anything?)

thanks

**Comment by rhazor** [comment]
http://download.tsi.telecom-paristech.fr/gpac/latest_builds/win64/gpac-0.7.2-DEV-rev25-g1f272a9-master-x64.exe

deleted user paths only, all my shit was in user paths like ffmpeg, eac3to and others, and was gone after install. I know that because next thing i was doing was running some commands and suddenly none are recognized, look up the paths, yup, all gone.

win10x64

**Comment by p-lucero** [comment]
+1ing this. System PATH is unaffected, but user PATH gets totally wiped and replaced with three entries of the GPAC directory, just as in rhazor's screenshot. Occurs on GPAC stable 0.7.0 for Windows, running Windows 10 x64. I think that it may be due to the way that [AddToPath](https://github.com/gpac/gpac/blob/39c7f0e7ceb5fd4b5f18b9b62e38da0596be0f4d/packagers/win32_64/nsis/gpac_installer.nsi#L691) performs in the install script. I've never worked with the Nullsoft scripting thing that is in use here, but it seems like there are values that are pushed onto the stack that don't get popped off, and restoring the variables $1, $2, $3 is going to not function properly at the end of the function. However, that's just a semi-educated guess, as I really don't have the first clue what's actually going on here.

**Comment by aureliendavid** [comment]
well, it turns out this is a known issue of NSIS : http://nsis.sourceforge.net/Path_Manipulation#Warning

to sum up: 

* NSIS has a max string length of 1024 (!)
* they provide special builds where to limit is 8k
* function calls (including ReadEnvVar used to read the PATH) return an empty string in case of overflow, without any indication of an error (!)

all this means when we try appending to a PATH longer than 1024 we actually erase the existing PATH and add ours - this is bad

there is a way to do it properly by using system calls to check the length instead of trying to read the whole PATH in a string, it seems to work well on any windows version >= 2000. 

it seems to me that it's more reasonable to drop support for prehistoric versions rather than risking destructive behavior


fixes:

* I installed the special builds of NSIS on the windows build machines - it supports strings up to 8k (windows usually limits the PATH length to 2k, but it can actually grow larger so this point is not sufficient)
* I changed the AddToPath function in the installer script - if the PATH grows too big it will now alert the user during the install and not try to add to PATH (the install still works but the PATH editing would need to be done manually)
* the new function also fixes the fact that we used to add the install dir 3 times in the PATH (one for each executable)
* fixing this also fixes the uninstall script (we used to remove it once even if we wrote it 3 times)


thanks for the reports

(please reopen the issue if there is a problem with any of the above)
