### ISSUE TITLE
error when batch extract streams from various files

### ISSUE THREAD

**Issue by bebertii** [gpac/gpac#893]
Hi,
I'm trying to extract audio stream from some MP4 files located in a same folder, so I tried the command 
`FOR /R %G IN (*.mp4) DO "c:\program files (x86)\GPAC\mp4box" - raw 2 %G`
The command tries the extraction for each file, but always with an error
`c:\program files (x86)\GPAC\mp4box" -raw 2 "working_dir\file.mp4
 Error - 2 input names specified, please check usage`

However, if I run the same command but written by me, it works, and I don't understand why

[EDIT] I use gpac-0.7.2-DEV-rev223-g06e9447-master-win32 on an updated W10

**Comment by aureliendavid** [comment]
you probably have filenames with spaces in them, so you need to escape them in quotes otherwise there are seen as multiple arguments

`FOR /R %G IN (*.mp4) DO "c:\program files (x86)\GPAC\mp4box" - raw 2 "%G"`

should work, on for more general cases see https://stackoverflow.com/questions/5553040/batch-file-for-loop-with-spaces-in-dir-name
