### ISSUE TITLE
Install from command line

### ISSUE THREAD

**Issue by diegocsandrim** [gpac/gpac#894]
How should I install GPAC from command line in windows?

I need to automate my machine configuration and installing GPAC programatically, so I expect to install it from command line.

Expected: call gpac.exe /quiet and it get installed
Actual: gpac is prompting a graphical interface to install
Platform: Windows 10 and Server 64bit
Build used: gpac-0.7.0-rev0-gbd5c9af-master-x64.exe

Also, an msi would be much easier to install in Windows machines, which already has option to install from command line.

**Comment by aureliendavid** [comment]
You can install gpac silently from the command line with 

`gpac-<version>.exe /S`

It will install with all default options. It also supports `/D=<INSTALL PATH>`.

The installer is an NSIS, some doc here : http://nsis.sourceforge.net/Docs/Chapter3.html#installerusage

There are no immediate plans to make it an msi, although I do agree that we should at some point since it's now the standard.

**Comment by felipecdo** [comment]
Thanks @aureliendavid and @diegocsandrim!

**Comment by diegocsandrim** [comment]
Thank you very much @aureliendavid!
