### ISSUE TITLE
configure and static builds

### ISSUE THREAD

**Issue by aureliendavid** [gpac/gpac#897]
(I'm putting this here instead of writing a long commit message) 

When running configure with` --static-modules` or `--enable-static-bin`, the `static.mak` puts all necessary include dirs (`-I`) on the gcc command line. 

If OpenSVCDec is detected present, it will add `-Iextra_lib/include` to the command line : https://github.com/gpac/gpac/blob/master/configure#L1072

So now the headers in `extra_lib/include` will all have higher priority than the system ones (see: https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html#Directory-Options).

In particular, in `utils/downloader.c`, when we `#include <openssl/ssl.h>`, it's the version in `extra_lib/include` that will be included. But this version seem to only be for windows (https://github.com/gpac/gpac/blob/master/extra_lib/include/openssl/opensslconf.h#L5). 

The only way for system headers to have a higher priority than local header is to use `-idirafter` instead of `-I`.

**Comment by rbouqueau** [comment]
The presence of -Iextra_lib/include is a legacy from old times when people on Windows wanted to build mp4box or mp42ts without having the burden of setting the extra libs.

Now this time is almost over:

 1) We should provide stronger scripts for extra_lib install.
 2) We could empty extra_lib/ them because:
   i) It should be filled by the configure script on Unix
   ii) Windows users should have the choice between two sln (mp4box static only and full gpac (could we add a check when opening the sln for extra_lib file presence?)). This could be related to a migration to another build system (CMake?) although this would be a huge work to support all platforms.
