### ISSUE TITLE
Osmo4 (0.7.2-DEV nightly build) segmentation fault: 11 - Couldn't init semaphore: error 28 when running in LowLatency=chunk mode

### ISSUE THREAD

**Issue by doma0164** [gpac/gpac#918]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X ] I looked for a similar issue and couldn't find any.
- [X ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Issue Descriptions:
I am using the Osmo4 player on my MacBook Pro to play back a DASH mpd file in chunk LowLatency mode. After running for a while (varied from a few minutes to 1-2 hours), the player exits due to a segmentation fault. When this happens, the player will always exits with the same error when I try to re-start it, until I reboot my laptop.

Here are my command line options:
$ /Applications/Osmo4.app/Contents/MacOS/Osmo4 http://10.91.112.125:8888/llabr/dcmcap/dash.mpd -opt Network:BufferLength=800 -opt DASH:LowLatency=chunk -opt DASH:UseServerUTC=no
Using config file in /Users/doma/.gpac directory
System info: 16384 MB RAM - 8 cores
Modules Found : 36
Loading GPAC Terminal
Terminal Loaded in 647 ms
Opening URL http://10.91.112.125:8888/llabr/dcmcap/dash.mpd
Couldn't init semaphore: error 28
Segmentation fault: 11

The Problem Report is attached here:

[ProglemReport.txt](https://github.com/gpac/gpac/files/1373209/ProglemReport.txt)

**Comment by aureliendavid** [comment]
Ok it seems to be an OSX specific problem. From what I can gather on a first pass:

The last error 

`Couldn't init semaphore: error 28`

means

`#define ENOSPC      28  /* No space left on device */`

So it seems like some partition is filling up preventing us from creating a new semaphore. 

It seems like OSX have a global limit on the number of semaphores created. Also OSX doesn't support unnamed semaphores (created with `sem_init`) but only named semaphores (created with `sem_open`).

However it seems like the actual file associated to a named semaphore isn't cleaned when calling `sem_close`. Additionally they're aren't cleaned when the process exists uncleanly. 

That's why when MP4Client segfaults after filling up the semaphore limit, the following executions fail too and a reboot is needed. 

[unnamed semaphores, created by `sem_init()` and used on linux, are cleaned by `sem_destroy()`, but it can't be used on named ones because that would be too easy...]

The solution seem to be adding a call to `sem_unlink()` before `sem_close()` to remove the actual file. Also we shouldn't segfault on this kind of error. 

This is all speculation for now, I haven't tested anything yet. I'll try to reproduce the problem.

**Comment by aureliendavid** [comment]
I couldn't reproduce the exact issue but I fixed what I believe to be the problem. 

@doma0164 Can you test again with the latest version and tell us if it's still happening ?

**Comment by donghaima** [comment]
Thank you Aurélien for the quick fix! I have been running the player which has your fix for over a day now. So far I haven't seen it recurring.
