### ISSUE TITLE
First sidx duration for audio is too small when producing DASH OnDemand content

### ISSUE THREAD

**Issue by TobbeEdgeware** [gpac/gpac#931]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

When creating DASH OnDemand content like:

    MP4Box -dash 4000 -profile onDemand -out manifest.mpd A9.mp4:id=A9 V8000.mp4:id=V8000

the duration of the first entry in the sidx box gets a value which is smaller than the actual subsegment's duration. In this example 189,440 instead of the correct value 191,488 which all other subsegments have. All subsegments have 187 samples, but the first sidx duration indicates 185 samples.

**Comment by aureliendavid** [comment]
Hi, 

I think this is not really a bug. 

As it turns out, your input file has an "edit list" box (`elst`) which, if I understand the mpeg spec correctly, is used to map the media timeline to the presentation timeline. Here the value is 2048 meaning that we get the presentation time by subtracting 2048 to the media time. 

_[I don't know why this exists, but it looks like it does - You can see it with MP4Box -diso A9.mp4]_

Now the `subsegment_duration` field of the `sidx` box is calculated by the difference, **in presentation time**, between the start of the next subsegment and the start of the current one.

However, since the presentation time cannot be less than 0, the 2048 offset will be taken off the start of every segment **except the first one**. So you'll have 

```
subsegment_duration1 = (191488 - 2048) - 0               = 189440
subsegment_duration2 = (382976 - 2048) - (191488 - 2048) = 191488
...
```

When running with debug logs 

`MP4Box -dash 4000 -profile onDemand -out manifest.mpd A9.mp4 -logs dash@debug`

we can see that the first fragment actually have the right size of 191488. It's just the way to express it in the sidx box that's weird.
